-----------------------------------------------------------------------------------------------------------------------------------------
-- LIST
-----------------------------------------------------------------------------------------------------------------------------------------
local List = {
	["creditcard"] = {
		["Index"] = "creditcard",
		["Name"] = "Cartão de Crédito",
		["Type"] = "Comum",
		["Weight"] = 0.25
	},
	["diagram"] = {
		["Index"] = "diagram",
		["Name"] = "Diagrama",
		["Type"] = "Comum",
		["Weight"] = 0.75
	},
	["propertys"] = {
		["Index"] = "propertys",
		["Name"] = "Cartão de Segurança",
		["Type"] = "Comum",
		["Weight"] = 0.35
	},
	["grinder"] = {
		["Index"] = "grinder",
		["Name"] = "Grinder",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.25,
	},
	["bennys"] = {
		["Index"] = "bennys",
		["Name"] = "Ticket Bennys",
		["Type"] = "Comum",
		["Durability"] = 0.005,
		["Weight"] = 3.25
	},
	["megaphone"] = {
		["Index"] = "megaphone",
		["Name"] = "Megafone",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 3.25
	},
	["sprays01"] = {
		["Index"] = "sprays",
		["Name"] = "Spray",
		["Type"] = "Usável",
		["Weight"] = 0.75
	},
	["sprays02"] = {
		["Index"] = "sprays",
		["Name"] = "Spray de tinta",
		["Description"] = "Spray para pintura de superfícies.",
		["Type"] = "Usável",
		["Weight"] = 0.75
	},
	["backpack"] = {
		["Index"] = "backpack",
		["Name"] = "Mochila",
		["Description"] = "Mochila inicial 50kl adicionais.",
		["Type"] = "Usável",
		["Weight"] = 0.75
	},
	["tinner"] = {
		["Index"] = "tinner",
		["Name"] = "Thinner",
		["Description"] = "Solvente para remoção de tinta.",
		["Type"] = "Usável",
		["Weight"] = 0.75
	},
	["enginea"] = {
		["Index"] = "enginea",
		["Name"] = "Motor",
		["Type"] = "Usável",
		["Weight"] = 9.25
	},
	["engineb"] = {
		["Index"] = "engineb",
		["Name"] = "Motor",
		["Type"] = "Usável",
		["Weight"] = 10.25
	},
	["enginec"] = {
		["Index"] = "enginec",
		["Name"] = "Motor",
		["Type"] = "Usável",
		["Weight"] = 11.25
	},
	["engined"] = {
		["Index"] = "engined",
		["Name"] = "Motor",
		["Type"] = "Usável",
		["Weight"] = 12.25
	},
	["enginee"] = {
		["Index"] = "enginee",
		["Name"] = "Motor",
		["Type"] = "Usável",
		["Weight"] = 13.25
	},
	["transmissiona"] = {
		["Index"] = "transmissiona",
		["Name"] = "Transmissão",
		["Type"] = "Usável",
		["Weight"] = 9.25
	},
	["transmissionb"] = {
		["Index"] = "transmissionb",
		["Name"] = "Transmissão",
		["Type"] = "Usável",
		["Weight"] = 10.25
	},
	["transmissionc"] = {
		["Index"] = "transmissionc",
		["Name"] = "Transmissão",
		["Type"] = "Usável",
		["Weight"] = 11.25
	},
	["transmissiond"] = {
		["Index"] = "transmissiond",
		["Name"] = "Transmissão",
		["Type"] = "Usável",
		["Weight"] = 12.25
	},
	["transmissione"] = {
		["Index"] = "transmissione",
		["Name"] = "Transmissão",
		["Type"] = "Usável",
		["Weight"] = 13.25
	},
	["brakea"] = {
		["Index"] = "brakea",
		["Name"] = "Freios",
		["Type"] = "Usável",
		["Weight"] = 7.25
	},
	["brakeb"] = {
		["Index"] = "brakeb",
		["Name"] = "Freios",
		["Type"] = "Usável",
		["Weight"] = 8.25
	},
	["brakec"] = {
		["Index"] = "brakec",
		["Name"] = "Freios",
		["Type"] = "Usável",
		["Weight"] = 9.25
	},
	["braked"] = {
		["Index"] = "braked",
		["Name"] = "Freios",
		["Type"] = "Usável",
		["Weight"] = 10.25
	},
	["brakee"] = {
		["Index"] = "brakee",
		["Name"] = "Freios",
		["Type"] = "Usável",
		["Weight"] = 11.25
	},
	["suspensiona"] = {
		["Index"] = "suspensiona",
		["Name"] = "Suspensão",
		["Type"] = "Usável",
		["Weight"] = 7.25
	},
	["suspensionb"] = {
		["Index"] = "suspensionb",
		["Name"] = "Suspensão",
		["Type"] = "Usável",
		["Weight"] = 8.25
	},
	["suspensionc"] = {
		["Index"] = "suspensionc",
		["Name"] = "Suspensão",
		["Type"] = "Usável",
		["Weight"] = 9.25
	},
	["suspensiond"] = {
		["Index"] = "suspensiond",
		["Name"] = "Suspensão",
		["Type"] = "Usável",
		["Weight"] = 10.25
	},
	["suspensione"] = {
		["Index"] = "suspensione",
		["Name"] = "Suspensão",
		["Type"] = "Usável",
		["Weight"] = 11.25
	},
	["dismantle"] = {
		["Index"] = "dismantle",
		["Name"] = "Contrato",
		["Description"] = "Ativando o mesmo você assume a responsabilidade com o <b>Lester</b> de desmanchar um veículo.",
		["Type"] = "Usável",
		["Weight"] = 0.75,
		["Max"] = 3
	},
	["repairkit01"] = {
		["Index"] = "repairkit01",
		["Name"] = "Kit de Reparos - Comum",
		["Type"] = "Comum",
		["Weight"] = 3.25,
	},
	["repairkit02"] = {
		["Index"] = "repairkit02",
		["Name"] = "Kit de Reparos",
		["Type"] = "Comum",
		["Weight"] = 3.75,
	},
	["repairkit03"] = {
		["Index"] = "repairkit03",
		["Name"] = "Bateria AA",
		["Type"] = "Comum",
		["Weight"] = 1.25,
	},
	["repairkit04"] = {
		["Index"] = "repairkit04",
		["Name"] = "Power Bank",
		["Type"] = "Comum",
		["Weight"] = 1.75,
	},
	-- ["bolsapreta"] = {
	-- 	["Index"] = "bolsapreta",
	-- 	["Name"] = "Mochila Premium",
	-- 	["Description"] = "Aumenta mochila para 150KL.",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["mochilaenergetico"] = {
	-- 	["Index"] = "mochilaenergetico",
	-- 	["Name"] = "Mochila Energetico",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["mochilamilitar"] = {
	-- 	["Index"] = "mochilamilitar",
	-- 	["Name"] = "Mochila Militar",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["mochilaoriental"] = {
	-- 	["Index"] = "mochilaoriental",
	-- 	["Name"] = "Mochila Oriental",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["mochilacouropreta"] = {
	-- 	["Index"] = "mochilacouropreta",
	-- 	["Name"] = "Mochila de Couro Preta",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["mochilacouro"] = {
	-- 	["Index"] = "mochilacouro",
	-- 	["Name"] = "Mochila de Couro",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["cachorrinhobeje"] = {
	-- 	["Index"] = "cachorrinhobeje",
	-- 	["Name"] = "Mochila Cachorinho Beje",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	-- ["cachorrinhoazul"] = {
	-- 	["Index"] = "cachorrinhoazul",
	-- 	["Name"] = "Mochila Cachorrinho Azul",
	-- 	["Type"] = "Usável",
	-- 	["Weight"] = 5.25,
	-- },
	["paper"] = {
		["Index"] = "paper",
		["Name"] = "Papel",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["rentalveh"] = {
		["Index"] = "rentalveh",
		["Name"] = "Aluguel de Veículo",
		["Description"] = "Leve até a concessionária para usa-lo.",
		["Type"] = "Usável",
		["Weight"] = 0.15,
	},
	["mushroomteaplus"] = {
		["Index"] = "mushroomtea",
		["Name"] = "Chá de Cogumelo",
		["Description"] = "Aumenta a mochila em 10Kg.",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["c4"] = {
		["Index"] = "c4",
		["Name"] = "Bomba Caseira",
		["Type"] = "Usável",
		["Weight"] = 2.75,
		["Max"] = 3,
	},
	["drill"] = {
		["Index"] = "drill",
		["Name"] = "Furadeira",
		["Type"] = "Usável",
		["Weight"] = 2.75,
		["Max"] = 3,
	},
	["c4b9"] = {
		["Index"] = "explosives",
		["Name"] = "Explosivo Rb",
		["Type"] = "Usável",
		["Weight"] = 2.75,
		["Max"] = 3,
	},
	["geode"] = {
		["Index"] = "geode",
		["Name"] = "Geodo",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["pickaxe"] = {
		["Index"] = "pickaxe",
		["Name"] = "Picareta",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 2.25,
	},
	["oab"] = {
		["Index"] = "oab01",
		["Name"] = "OAB",
		["Description"] = "<green></green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badgecnn"] = {
		["Index"] = "badgecnn",
		["Name"] = "Funcional",
		["Description"] = "<green>CNN</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge01"] = {
		["Index"] = "badge01",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Militar</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge02"] = {
		["Index"] = "badge02",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Civil</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge03"] = {
		["Index"] = "badge03",
		["Name"] = "Distintivo",
		["Description"] = "<green>Bombeiro</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge04"] = {
		["Index"] = "badge04",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Federal</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge05"] = {
		["Index"] = "badge05",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Rodoviaria Federal</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge06"] = {
		["Index"] = "badge06",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Penal</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge07"] = {
		["Index"] = "badge07",
		["Name"] = "Distintivo",
		["Description"] = "<green>Polícia Municipal</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["badge08"] = {
		["Index"] = "badge08",
		["Name"] = "Distintivo",
		["Description"] = "<green>Exercito</green>",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["mushroomtea"] = {
		["Index"] = "mushroomtea",
		["Name"] = "Chá de Cogumelo",
		["Description"] = "Tempo pedalando reduzido para <green>10 minutos</green> por <green>60 minutos</green>, lembrando que o efeito passa desconectando da cidade.",
		["Durability"] = 1,
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["filedepeixe"] = {
		["Index"] = "filedepeixe",
		["Name"] = "Filé de pescada com fritas",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.65,
	},
	["bife"] = {
		["Index"] = "bife",
		["Name"] = "Bife com fritas",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.65,
		["Max"] = 10,
	},
	["milkshake"] = {
		["Index"] = "milkshake",
		["Name"] = "Milk Shake",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.8555,
		["Scape"] = true,
		["Max"] = 10,
	},
	["cappuccino"] = {
		["Index"] = "cappuccino",
		["Name"] = "Cappuccino",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.65,
		["Scape"] = true,
		["Max"] = 10,
	},
	["credential"] = {
		["Index"] = "credential",
		["Name"] = "Credencial",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["racetrophy"] = {
		["Index"] = "racetrophy",
		["Name"] = "Troféu",
		["Type"] = "Comum",
		["Weight"] = 7.25,
	},
	["nitro"] = {
		["Index"] = "nitro",
		["Name"] = "Nitro",
		["Type"] = "Usável",
		["Weight"] = 7.25,
	},
	["attachsFlashlight"] = {
		["Index"] = "attachsFlashlight",
		["Name"] = "Lanterna Tatica",
		["Type"] = "Usável",
		["Weight"] = 1.15,
		["Durability"] = 7
	},
	["attachsCrosshair"] = {
		["Index"] = "attachsCrosshair",
		["Name"] = "Mira Holográfica",
		["Type"] = "Usável",
		["Weight"] = 1.15,
		["Durability"] = 7
	},
	["attachsSilencer"] = {
		["Index"] = "attachsSilencer",
		["Name"] = "Silenciador",
		["Type"] = "Usável",
		["Weight"] = 1.15,
		["Durability"] = 7
	},
	["attachsMagazine"] = {
		["Index"] = "attachsMagazine",
		["Name"] = "Pente Estendido",
		["Type"] = "Usável",
		["Weight"] = 1.15,
		["Durability"] = 7
	},
	["attachsGrip"] = {
		["Index"] = "attachsGrip",
		["Name"] = "Empunhadura",
		["Type"] = "Usável",
		["Weight"] = 1.15,
		["Durability"] = 7
	},
	["cheese"] = {
		["Index"] = "cheese",
		["Name"] = "Queijo",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["silk"] = {
		["Index"] = "silk",
		["Name"] = "Seda",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["tablecoke"] = {
		["Index"] = "tablecoke",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Cocaína.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tablemeth"] = {
		["Index"] = "tablemeth",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Metanfetamina.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tableweed"] = {
		["Index"] = "tableweed",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Baseados.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tablelean"] = {
		["Index"] = "leantable",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Lean.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tableecstasy"] = {
		["Index"] = "tableecstasy",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Ecstasy.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tabledry"] = {
		["Index"] = "tableweed",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Dry.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tableice"] = {
		["Index"] = "tableweed",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Ice.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tablek9"] = {
		["Index"] = "tableweed",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de K9.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["tablelanca"] = {
		["Index"] = "tableweed",
		["Name"] = "Mesa de Criação",
		["Description"] = "Utilizada para criação de Lanca.",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["campfire"] = {
		["Index"] = "campfire",
		["Name"] = "Fogueira",
		["Type"] = "Usável",
		["Weight"] = 5.75,
	},
	["barrier"] = {
		["Index"] = "barrier",
		["Name"] = "Barreira",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.75,
	},
	["cone"] = {
		["Index"] = "cone",
		["Name"] = "Cone",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.75,
	},
	["medicbag"] = {
		["Index"] = "medicbag",
		["Name"] = "Bolsa Médica",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 2.75,
	},
	["medicbed"] = {
		["Index"] = "medicbed",
		["Name"] = "Maca Médica",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 7.25,
	},
	["techtrash"] = {
		["Index"] = "techtrash",
		["Name"] = "Circuito Eletronico",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["chipset"] = {
		["Index"] = "chipset",
		["Name"] = "Chipset",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["antena"] = {
		["Index"] = "antena",
		["Name"] = "Antena de Wireless quebrada.",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["tarp"] = {
		["Index"] = "tarp",
		["Name"] = "Lona",
		["Type"] = "Comum",
		["Weight"] = 0.65,
	},
	["sheetmetal"] = {
		["Index"] = "sheetmetal",
		["Name"] = "Chapa de Metal",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["roadsigns"] = {
		["Index"] = "roadsigns",
		["Name"] = "Placas de Trânsito",
		["Type"] = "Comum",
		["Weight"] = 0.65,
	},
	["leather"] = {
		["Index"] = "leather",
		["Name"] = "Couro",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["lean"] = {
		["Index"] = "lean",
		["Name"] = "Lean",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	
	},
	["ecstasy"] = {
		["Index"] = "Ecstasy",
		["Name"] = "ecstasy",
		["Type"] = "Usável",
		["Weight"] = 0.10,
		
	},
	["explosives"] = {
		["Index"] = "explosives",
		["Name"] = "Explosivos",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["animalfat"] = {
		["Index"] = "animalfat",
		["Name"] = "Gordura Animal",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	-- ["fidentity"] = {
	-- 	["Index"] = "identity",
	-- 	["Name"] = "Passaporte",
	-- 	["Description"] = "",
	-- 	["Type"] = "Comum",
	-- 	["Weight"] = 0.15,
	-- },
	["identity"] = {
		["Index"] = "identity",
		["Name"] = "Rg",
		["Description"] = "",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		['Block'] = true
	},
	["blocksignal"] = {
		["Index"] = "blocksignal",
		["Name"] = "Bloqueador de Sinal",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["weaponbody"] = {
		["Index"] = "weaponbody",
		["Name"] = "Corpo de Arma",
		["Description"] = "Utilizado na fabricação de armas.",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	["triggerpistol"] = {
		["Index"] = "triggerpistol",
		["Name"] = "Gatilho de Pistola",
		["Type"] = "Comum",
		["Weight"] = 0.05,
	},
	["triggersmg"] = {
		["Index"] = "triggerpistol",
		["Name"] = "Gatilho de SMG",
		["Type"] = "Comum",
		["Weight"] = 0.05,
	},
	["triggerrifle"] = {
		["Index"] = "triggerpistol",
		["Name"] = "Gatilho de Rifle",
		["Type"] = "Comum",
		["Weight"] = 0.05,
	},
	["cotton"] = {
		["Index"] = "cotton",
		["Name"] = "Algodão",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["plaster"] = {
		["Index"] = "plaster",
		["Name"] = "Esparadrapo",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["sulfuric"] = {
		["Index"] = "sulfuric",
		["Name"] = "Ácido Sulfúrico",
		["Type"] = "Usável",
		["Weight"] = 0.01,
	},
	["saline"] = {
		["Index"] = "saline",
		["Name"] = "Soro Fisiológico",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["resetchar"] = {
		["Index"] = "resetchar",
		["Name"] = "Reset de Personagem",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		},
	["cnhA"] = {
		["Index"] = "cnh",
		["Name"] = "Carteira de Habilitação A",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		["Durability"] = 30,
	},
	["cnhB"] = {
		["Index"] = "cnh",
		["Name"] = "Carteira de Habilitação B",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		["Durability"] = 30,
	},
	["cnhC"] = {
		["Index"] = "cnh",
		["Name"] = "Carteira de Habilitação C",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		["Durability"] = 30,
	},
	["cnhD"] = {
		["Index"] = "cnh",
		["Name"] = "Carteira de Habilitação D",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		["Durability"] = 30,
	},
	["defibrillator"] = {
		["Index"] = "defibrillator",
		["Name"] = "Desfibrilador",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 3,
		["Weight"] = 3.75,
	},
	["casino_vip"] = {
		["Index"] = "casino_vip",
		["Name"] = "Ingresso Vip Cassino",
		["Type"] = "Comum",
		["Weight"] = 1.0,
		["Durability"] = 1,
	},
	["casino_member"] = {
		["Index"] = "casino_member",
		["Name"] = "Ingresso Cassino",
		["Type"] = "Comum",
		["Weight"] = 1.0,
		["Durability"] = 1,
	},
	["casinochips"] = {
		["Index"] = "casinochips",
		["Name"] = "Fichas Cassino",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["alcohol"] = {
		["Index"] = "alcohol",
		["Name"] = "Álcool",
		["Type"] = "Comum",
		["Weight"] = 0.65,
	},
	["kitupgrade"] = {
		["Index"] = "kitupgrade",
		["Name"] = "kit upgrade",
		["Type"] = "Usável",
		["Weight"] = 7.25,
		["Description"] = "Kit instalação de Suspensão a AR e Neon.",
	},
	["verify"] = {
		["Index"] = "instaverify",
		["Name"] = "Instagram Verificado",
		["Description"] = "Recebe o Selo de Verificado no <br>Instagram</b>",
		["Type"] = "Usável",
		["Weight"] = 0.15,
	},
	["gruppesechstablet"] = {
		["Index"] = "gruppesechstablet",
		["Name"] = "Tablet Seguradora",
		["Description"] = "Tablet.",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tabletorg"] = {
		["Index"] = "tabletorg",
		["Name"] = "Tablet de orgs",
		["Description"] = "Utilizado para acessar o sistema de organizações.",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.25,
	},
	["drugtable"] = {
		["Index"] = "tablecoke",
		["Name"] = "Mesa de Droga",
		["Description"] = "Mesa para venda de drogas.",
		["Type"] = "Usável",
		["Durability"] = 3,
		["Weight"] = 3.00,
	},
	["drugtable2"] = {
		["Index"] = "tablecoke",
		["Name"] = "Mesa de Droga Lacrada",
		["Description"] = "Mesa para venda de drogas.",
		["Type"] = "Usável",
		["Weight"] = 3.00,
	},
	["macbook"] = {
		["Index"] = "macbook",
		["Name"] = "Notebook de Piloto Clandestino",
		["Description"] = "Notebook especial para corrida clandestina.",
		["Type"] = "Usável",
		["Durability"] = 3,
		["Weight"] = 7.25,
	},
	["syringe"] = {
		["Index"] = "syringe",
		["Name"] = "Seringa",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	["syringe01"] = {
		["Index"] = "syringe2",
		["Name"] = "Seringa A+",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["syringe02"] = {
		["Index"] = "syringe2",
		["Name"] = "Seringa B+",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["syringe03"] = {
		["Index"] = "syringe2",
		["Name"] = "Seringa A-",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["syringe04"] = {
		["Index"] = "syringe2",
		["Name"] = "Seringa B-",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["espetinhodepeixe"] = {
		["Index"] = "espetinhodepeixe",
		["Name"] = "espetinho de peixe",
		["Type"] = "Comum",
		["Weight"] = 0.25,
		["Max"] = 10,
		["Durability"] = 1,
	},
	["pizzathis3"] = {
		["Index"] = "pizzathis3",
		["Name"] = "Combo",
		["Type"] = "Comum",
		["Weight"] = 1.25,
		["Max"] = 2,
	},
	["Moquecadepeixe"] = {
		["Index"] = "Moquecadepeixe",
		["Name"] = "Moqueca de peixe",
		["Type"] = "Comum",
		["Weight"] = 1.25,
		["Max"] = 10,
		["Durability"] = 1,

	},
	["igredientesbebida"] = {
		["Index"] = "beanmachine1",
		["Name"] = "Ingredientes Bebida",
		["Type"] = "Comum",
		["Weight"] = 0.25,
		["Max"] = 1,
	},
	["igredientescomida"] = {
		["Index"] = "beanmachine2",
		["Name"] = "Ingredientes Comida",
		["Type"] = "Comum",
		["Weight"] = 0.25,
		["Max"] = 1,
	},
	["beanmachine3"] = {
		["Index"] = "beanmachine3",
		["Name"] = "Combo",
		["Type"] = "Comum",
		["Weight"] = 1.25,
		["Max"] = 2,
	},
	["beanmachine4"] = {
		["Index"] = "beanmachine3",
		["Name"] = "Combo + Brinquedo",
		["Type"] = "Comum",
		["Weight"] = 1.25,
		["Max"] = 2,
	},
	["spikestrip"] = {
		["Index"] = "spikestrip",
		["Name"] = "Spike",
		["Type"] = "Usável",
		["Weight"] = 5.0,
	},
	["bodycam"] = {
        ["Index"] = "bodycam",
        ["Name"] = "Camera Corporal",
        ["Description"] = "Camera Corporal para Policia",
        ["Type"] = "Usável",
        ["Weight"] = 0.10,
        ["Max"] = 1
    },
	["a"] = {
		["Index"] = "wheelchair",
		["Name"] = "Cadeira de Rodas",
		["Type"] = "Usável",
		["Weight"] = 7.25,
		["Block"] = true,
	},
	["vehkey"] = {
		["Index"] = "vehkey",
		["Name"] = "Chave Cópia",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["evidence01"] = {
		["Index"] = "evidence01",
		["Name"] = "Evidência DNA",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["evidence02"] = {
		["Index"] = "evidence02",
		["Name"] = "Evidência",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["evidence03"] = {
		["Index"] = "evidence03",
		["Name"] = "Evidência",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["evidence04"] = {
		["Index"] = "evidence04",
		["Name"] = "Evidência Balistica",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["card01"] = {
		["Index"] = "card01",
		["Name"] = "Cartão Comum",
		["Description"] = "Roubar Lojas de Departamento.",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.25,
	},
	["card02"] = {
		["Index"] = "card02",
		["Name"] = "Cartão In-Comum",
		["Description"] = "Roubar Lojas de Armas.",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.25,
	},
	["oil"] = {
		["Index"] = "oil",
		["Name"] = "Engine Oil",
		["Description"] = "Óleo para o motor do seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["tires"] = {
		["Index"] = "tires",
		["Name"] = "Tires",
		["Description"] = "Pneus para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 3,
	},
	["brake_pads"] = {
		["Index"] = "brake_pads",
		["Name"] = "Brake Pads",
		["Descriptionription"] = "Pastilhas de freio para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["transmission_oil"] = {
		["Index"] = "transmission_oil",
		["Name"] = "Transmission Oil",
		["Description"] = "Óleo de transmissão para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["shock_absorber"] = {
		["Index"] = "shock_absorber",
		["Name"] = "Shock Absorber",
		["Description"] = "Amortecedor para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["clutch"] = {
		["Index"] = "clutch",
		["Name"] = "Clutch",
		["Description"] = "Embreagem para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["air_filter"] = {
		["Index"] = "air_filter",
		["Name"] = "Air Filter",
		["Description"] = "Filtro de ar para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["fuel_filter"] = {
		["Index"] = "fuel_filter",
		["Name"] = "Fuel Filter",
		["Description"] = "Filtro de combustível para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["spark_plugs"] = {
		["Index"] = "spark_plugs",
		["Name"] = "Spark Plugs",
		["Description"] = "Velas de ignição para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["serpentine_belt"] = {
		["Index"] = "serpentine_belt",
		["Name"] = "Serpentine Belt",
		["Description"] = "Correia do alternador para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["susp"] = {
		["Index"] = "susp",
		["Name"] = "Lowered Suspension",
		["Description"] = "Suspensão rebaixada para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 5,
	},
	["susp1"] = {
		["Index"] = "susp1",
		["Name"] = "Stanced Suspension",
		["Description"] = "Suspensão stance para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 5,
	},
	["susp2"] = {
		["Index"] = "susp2",
		["Name"] = "Sport Suspension",
		["Description"] = "Suspensão esportiva para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 5,
	},
	["susp3"] = {
		["Index"] = "susp3",
		["Name"] = "Confort Suspension",
		["Description"] = "Suspensão confort para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 5,
	},
	["susp4"] = {
		["Index"] = "susp4",
		["Name"] = "Lifted Suspension",
		["Description"] = "Suspensão elevada para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 5,
	},
	["garett"] = {
		["Index"] = "garett",
		["Name"] = "Garett GTW Turbo",
		["Description"] = "Turbo Garett GTW para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["drone"] = {
		["Index"] = "drone",
		["Name"] = "Drone",
		["Description"] = "Drone.",
		["Type"] = "Usável",
		["Weight"] = 1,
		["Max"] = 1
	},
	["dronepolice"] = {
		["Index"] = "dronepolice",
		["Name"] = "Drone Policial",
		["Description"] = "Drone Policial.",
		["Type"] = "Usável",
		["Weight"] = 1,
		["Max"] = 1
	},
	["nitrous"] = {
		["Index"] = "nitrous",
		["Name"] = "Nitro",
		["Description"] = "Nitro para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["awd"] = {
		["Index"] = "awd",
		["Name"] = "Tração AWD",
		["Description"] = "Conversão para tração nas quatro rodas para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["rwd"] = {
		["Index"] = "rwd",
		["Name"] = "Tração RWD",
		["Description"] = "Conversão para tração traseira para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["fwd"] = {
		["Index"] = "fwd",
		["Name"] = "Tração FWD",
		["Description"] = "Conversão para tração dianteira para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 10,
	},
	["k20a"] = {
		["Index"] = "k20a",
		["Name"] = "K20",
		["Description"] = "Motor K20.",
		["Type"] = "Usável",
		["Weight"] = 10,
	},
	["911t"] = {
		["Index"] = "911t",
		["Name"] = "911T",
		["Description"] = "Motor 911.",
		["Type"] = "Usável",
		["Weight"] = 10,
	},
	["rb26"] = {
		["Index"] = "rb26",
		["Name"] = "RB26DETT",
		["Description"] = "Motor RB26DETT.",
		["Type"] = "Usável",
		["Weight"] = 10,
	},
	["2jz"] = {
		["Index"] = "2jz",
		["Name"] = "2JZ-GTE",
		["Description"] = "Motor 2JZ-GTE.",
		["Type"] = "Usável",
		["Weight"] = 10,
	},
	["semislick"] = {
		["Index"] = "semislick",
		["Name"] = "Pneu Semi Slick",
		["Description"] = "Pneus semi slick para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 6,
	},
	["slick"] = {
		["Index"] = "slick",
		["Name"] = "Pneu Slick",
		["Description"] = "Pneus slick para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 6,
	},
	["race_brakes"] = {
		["Index"] = "race_brakes",
		["Name"] = "Freios Corrida",
		["Description"] = "Freios Brembo para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 2,
	},
	["piston"] = {
		["Index"] = "piston",
		["Name"] = "Pistão",
		["Description"] = "Pistão para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["rod"] = {
		["Index"] = "rod",
		["Name"] = "Bielas",
		["Description"] = "Bielas para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["gear"] = {
		["Index"] = "gear",
		["Name"] = "Gear",
		["Description"] = "Engrenagem para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["brake_discs"] = {
		["Index"] = "brake_discs",
		["Name"] = "Brake Disc",
		["Description"] = "Disco de freio para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 0.20,
	},
	["brake_caliper"] = {
		["Index"] = "brake_caliper",
		["Name"] = "Brake Caliper",
		["Description"] = "Pinça de freio para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["springs"] = {
		["Index"] = "springs",
		["Name"] = "Springs",
		["Description"] = "Molas para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["iron"] = {
		["Index"] = "iron",
		["Name"] = "Iron",
		["Description"] = "Ferro para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["aluminum"] = {
		["Index"] = "aluminum",
		["Name"] = "Aluminum",
		["Description"] = "Alumínio.",
		["Type"] = "Usável",
		["Weight"] = 0.01,
	},
	["scanner"] = {
		["Index"] = "scanner",
		["Name"] = "Scanner",
		["Description"] = "Scanner para o seu carro.",
		["Type"] = "Usável",
		["Weight"] = 1,
	},
	["card03"] = {
		["Index"] = "card03",
		["Name"] = "Cartão Épico",
		["Description"] = "Roubar Bancos Fleeca.",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.25,
	},
	["card04"] = {
		["Index"] = "card04",
		["Name"] = "Cartão Raro",
		["Description"] = "Roubar Barbearias.",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.25,
	},
	["card05"] = {
		["Index"] = "card05",
		["Name"] = "Cartão Lendário",
		["Description"] = "Roubar Bancos.",
		["Repair"] = "repairkit01",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.25,
	},
	["gemstone"] = {
		["Index"] = "gemstone",
		["Name"] = "Gemstone",
		["Type"] = "Usável",
		["Weight"] = 0.15,
	},
	["radio"] = {
		["Index"] = "radio",
		["Name"] = "Rádio",
		["Type"] = "Usável",
		["Repair"] = "repairkit03",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["vest"] = {
		["Index"] = "vest",
		["Name"] = "Colete Policial",
		["Type"] = "Usável",
		["Durability"] = 10,
		["Weight"] = 3.75,
		["Max"] = 2,
	},
	["faixa"] = {
		["Index"] = "faixa",
		["Name"] = "Faixa Policial",
		["Description"] = "Faixa Policial.",
		["Type"] = "Usável",
		["Weight"] = 1,
		["Max"] = 1
	},
	["vest2"] = {
		["Index"] = "vest2",
		["Name"] = "Colete a prova de balas",
		["Type"] = "Usável",
		["Durability"] = 10,
		["Weight"] = 3.75,
		["Max"] = 1,
	},
	["bandage"] = {
		["Index"] = "bandage",
		["Name"] = "Bandagem",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["medkit"] = {
		["Index"] = "medkit",
		["Name"] = "Kit Médico",
		["Type"] = "Usável",
		["Weight"] = 0.75,
		["Max"] = 10,
	},
	["medkit1"] = {
		["Index"] = "medkit1",
		["Name"] = "Kit Médico Profissional",
		["Type"] = "Usável",
		["Weight"] = 0.75
	},
	["kitlimpeza"] = {
		["Index"] = "kitlimpeza",
		["Name"] = "Kit de Limpeza Veicular",
		["Description"] = "Com apenas uma garrafa de água, seu carro novo de novo!",
		["Type"] = "Usável",
		["Weight"] = 0.25
	},
	["pouch"] = {
		["Index"] = "pouch",
		["Name"] = "Malote",
		["Type"] = "Comum",
		["Weight"] = 1.25,
	},
	["woodlog"] = {
		["Index"] = "woodlog",
		["Name"] = "Tora de Madeira",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["fishingrod"] = {
		["Index"] = "fishingrod",
		["Name"] = "Vara de Pescar",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 2.75,
	},
	["switchblade"] = {
		["Index"] = "switchblade",
		["Name"] = "Canivete",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Description"] = "Utilizada para remoção de carne.",
		["Durability"] = 7,
		["Weight"] = 0.75,
	},
	["octopus"] = {
		["Index"] = "octopus",
		["Name"] = "Polvo",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["shrimp"] = {
		["Index"] = "shrimp",
		["Name"] = "Camarão",
		["Type"] = "Comum",
		["Weight"] = 0.50,
	},
	["carp"] = {
		["Index"] = "carp",
		["Name"] = "Carpa",
		["Type"] = "Usável",
		["Weight"] = 0.50,
	},
	["codfish"] = {
		["Index"] = "codfish",
		["Name"] = "Bacalhau",
		["Type"] = "Usável",
		["Weight"] = 0.50,
	},
	["catfish"] = {
		["Index"] = "catfish",
		["Name"] = "Bagre",
		["Type"] = "Usável",
		["Weight"] = 0.50,
	},
	["goldenfish"] = {
		["Index"] = "goldenfish",
		["Name"] = "Dourado",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["horsefish"] = {
		["Index"] = "horsefish",
		["Name"] = "Cavala",
		["Type"] = "Usável",
		["Weight"] = 0.50,
	},
	["tilapia"] = {
		["Index"] = "tilapia",
		["Name"] = "Tilápia",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["pacu"] = {
		["Index"] = "pacu",
		["Name"] = "Pacu",
		["Type"] = "Usável",
		["Weight"] = 0.50,
	},
	["pirarucu"] = {
		["Index"] = "pirarucu",
		["Name"] = "Pirarucu",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tambaqui"] = {
		["Index"] = "tambaqui",
		["Name"] = "Tambaqui",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["bait"] = {
		["Index"] = "bait",
		["Name"] = "Isca",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["animalpelt"] = {
		["Index"] = "animalpelt",
		["Name"] = "Pele Animal",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["weedclone"] = {
		["Index"] = "weedclone",
		["Name"] = "Semente de Maconha",
		["Type"] = "Usável",
		["Weight"] = 0.15
	},
	["ziplock"] = {
		["Index"] = "ziplock",
		["Name"] = "Saquinho",
		["Type"] = "Comum",
		["Weight"] = 0.01
	},
	["weedleaf"] = {
		["Index"] = "weedleaf",
		["Name"] = "Flor de Cannabis",
		["Type"] = "Comum",
		["Weight"] = 0.01
	},
	["joint"] = {
		["Index"] = "joint",
		["Name"] = "Porção de maconha",
		["Type"] = "Usável",
		["Weight"] = 0.10,
		
	},
	["ice"] = {
		["Index"] = "ice",
		["Name"] = "Ice",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	},
	["dry"] = {
		["Index"] = "dry",
		["Name"] = "Porção de dry",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	},
	["k9"] = {
		["Index"] = "k9",
		["Name"] = "K9",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	},
	["baseado"] = {
		["Index"] = "baseado",
		["Name"] = "Cigarro da Blazeit",
		["Type"] = "Usável",
		["Weight"] = 0.01,
	
	},
	["codeine"] = {
		["Index"] = "codeine",
		["Name"] = "Codeína",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["amphetamine"] = {
		["Index"] = "amphetamine",
		["Name"] = "Anfetamina",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["cocaine"] = {
		["Index"] = "cocaine",
		["Name"] = "Cocaína",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	},
	["cokeleaf"] = {
		["Index"] = "cokeleaf",
		["Name"] = "Folha de Coca",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["meth"] = {
		["Index"] = "meth",
		["Name"] = "Metanfetamina",
		["Type"] = "Usável",
		["Weight"] = 0.10,
	},
	["metacloridrato"] = {
		["Index"] = "metacloridrato",
		["Name"] = "Metanfetamina Cloridrato",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["metaempacotar"] = {
		["Index"] = "metaempacotar",
		["Name"] = "Metanfetamina Não Embalada",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["hammer"] = {
		["Index"] = "hammer",
		["Name"] = "Martelo",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["metabase"] = {
		["Index"] = "metabase",
		["Name"] = "Base de Metanfetamina",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["acetone"] = {
		["Index"] = "acetone",
		["Name"] = "Acetona",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["drugtoy"] = {
		["Index"] = "drugtoy",
		["Name"] = "Brinquedo",
		["Type"] = "Comum",
		["Weight"] = 0.01,
	},
	["racao"] = {
		["Index"] = "racao",
		["Name"] = "Ração animal",
		["Type"] = "Usável",
		["Weight"] = 0.01,
	},
	["rolepass"] = {
		["Index"] = "rolepass",
		["Name"] = "Rolepass",
		["Type"] = "Usável",
		["Weight"] = 0.15,
	},
	["premium1"] = {
		["Index"] = "premium1",
		["Name"] = "Premium Bronze",
		["Description"] = "<green>Duração de 30 dias, Salario de R$5500, Preset premium adicional, isento taxa de garagem</green>",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		['Block'] = true
	},
	["premium2"] = {
		["Index"] = "premium2",
		["Name"] = "Premium Silver",
		["Description"] = "<green>Duração de 30 dias, Salario de R$7500, Preset premium adicional, isento taxa de garagem, 1 vaga na garagem, 1 placa personalizada.</green>",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		['Block'] = true
	},
	["premium3"] = {
		["Index"] = "premium3",
		["Name"] = "Premium Gold",
		["Description"] = "<green>Duração de 30 dias, Salario de R$9500, Preset premium adicional, isento taxa de garagem, 2 vaga na garagem, 2 placa personalizada, 1 chip, 50 gemas, 1 Mochila de Couro.</green>",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		['Block'] = true
	},
	["premiumplate"] = {
		["Index"] = "platepremium",
		["Name"] = "Placa Premium",
		["Type"] = "Usável",
		["Description"] = "Personaliza a placa do veículo.",
		["Weight"] = 0.75,
	},
	["newchars"] = {
		["Index"] = "newchars",
		["Name"] = "+1 Personagem",
		["Type"] = "Usável",
		["Description"] = "Limite de personagem em +1.",
		["Weight"] = 0.25,
		['Block'] = true
	},
	["namechange"] = {
		["Index"] = "namechange",
		["Name"] = "Troca de Nome",
		["Type"] = "Usável",
		["Description"] = "Troca o nome do personagem.",
		["Weight"] = 0.25,
		['Blocked'] = true
	},
	["milkbottle"] = {
		["Index"] = "milkbottle",
		["Name"] = "Garrafa de Leite",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Scape"] = true,
		["Max"] = 5,
	},
	["guarananatural"] = {
		["Index"] = "guarananatural",
		["Name"] = "Guaraná Natural",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["water"] = {
		["Index"] = "water",
		["Name"] = "Água",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Scape"] = true,
		["Max"] = 10,
	},
	["emptybottle"] = {
		["Index"] = "emptybottle",
		["Name"] = "Garrafa Vazia",
		["Type"] = "Comum",
		["Weight"] = 0.15,
		["Scape"] = true,
		["Max"] = 10,
	},
	["coffee"] = {
		["Index"] = "coffee",
		["Name"] = "Copo de Café",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 10,
		["Durability"] = 1,		
	},
	["energetico"] = {
		["Index"] = "energetico",
		["Name"] = "Energetico",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 3,
	},
	["coffeemilk"] = {
		["Index"] = "coffeemilk",
		["Name"] = "Café com Leite",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.35,
		["Max"] = 10,		
	},
	["cola"] = {
		["Index"] = "cola",
		["Name"] = "Coca Cola",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["vinho"] = {
		["Index"] = "vinho",
		["Name"] = "Vinho",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["royal"] = {
		["Index"] = "royal",
		["Name"] = "Royal Salute",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["redlabel"] = {
		["Index"] = "redlabel",
		["Name"] = "Red Label",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["passport"] = {
		["Index"] = "passport",
		["Name"] = "Passport",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["negroni"] = {
		["Index"] = "negroni",
		["Name"] = "Negroni",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["jackdaniels"] = {
		["Index"] = "jackmel",
		["Name"] = "Jack de Mel",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["beats"] = {
		["Index"] = "beats",
		["Name"] = "Skol Beats",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["chandom"] = {
		["Index"] = "chandom",
		["Name"] = "Chandom",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["vodka"] = {
		["Index"] = "vodka",
		["Name"] = "Vodka",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tanqueray"] = {
		["Index"] = "gintonica",
		["Name"] = "Gin Tonica",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["martini"] = {
		["Index"] = "martini",
		["Name"] = "Drink Martini",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["moscowmule"] = {
		["Index"] = "moscowmule",
		["Name"] = "Drink Moscow Mule",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["cerveja"] = {
		["Index"] = "cerveja",
		["Name"] = "Cerveja",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["corote"] = {
		["Index"] = "corote",
		["Name"] = "Corote",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["toddynho"] = {
		["Index"] = "toddynho",
		["Name"] = "Toddynho",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tacos"] = {
		["Index"] = "tacos",
		["Name"] = "Tacos",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.25,
		["Max"] = 10,		
	},
	["fries"] = {
		["Index"] = "fries",
		["Name"] = "Batata Frita",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.25,
		["Max"] = 10,		
	},
	["soda"] = {
		["Index"] = "soda",
		["Name"] = "Sprunk",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.25,
		["Max"] = 10,		
	},
	["apple"] = {
		["Index"] = "apple",
		["Name"] = "Maça",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["orange"] = {
		["Index"] = "orange",
		["Name"] = "Laranja",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["strawberry"] = {
		["Index"] = "strawberry",
		["Name"] = "Morango",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["coffee2"] = {
		["Index"] = "coffee2",
		["Name"] = "Grão de Café",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["grape"] = {
		["Index"] = "grape",
		["Name"] = "Uva",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tange"] = {
		["Index"] = "tange",
		["Name"] = "Tangerina",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["banana"] = {
		["Index"] = "banana",
		["Name"] = "Banana",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["guarana"] = {
		["Index"] = "guarana",
		["Name"] = "Guaraná",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["acerola"] = {
		["Index"] = "acerola",
		["Name"] = "Acerola",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["potato"] = {
		["Index"] = "potato",
		["Name"] = "Batata",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["alface"] = {
		["Index"] = "alface",
		["Name"] = "Alface",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["passion"] = {
		["Index"] = "passion",
		["Name"] = "Maracujá",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tomato"] = {
		["Index"] = "tomato",
		["Name"] = "Tomate",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["fenda"] = {
		["Index"] = "fenda",
		["Name"] = "Chave de fenda",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["key"] = {
		["Index"] = "fenda",
		["Name"] = "Chave da Prisão",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["sugar"] = {
		["Index"] = "sugar",
		["Name"] = "Açucar",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},

	["cupcake"] = {
		["Index"] = "cupcake",
		["Name"] = "Cupcake",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.55,
		["Max"] = 10,
	},
	["cookies"] = {
		["Index"] = "cookies",
		["Name"] = "Cookies",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["applelove"] = {
		["Index"] = "applelove",
		["Name"] = "Maça do Amor",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["bolochocolate"] = {
		["Index"] = "bolochocolate",
		["Name"] = "Bolo de Chocolate",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["paodequeijo"] = {
		["Index"] = "paodequeijo",
		["Name"] = "Pão de Queijo",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["donut"] = {
		["Index"] = "donut",
		["Name"] = "Donuts",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["tortasalgada"] = {
		["Index"] = "tortasalgada",
		["Name"] = "Torta Salgada",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["chagelado"] = {
		["Index"] = "chagelado",
		["Name"] = "Chá Gelado",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["lancaperfume"] = {
		["Index"] = "lancaperfume",
		["Name"] = "Lança Perfume",
		["Type"] = "Usável",
		["Weight"] = 0.10,	
	},
	["frappuccino"] = {
		["Index"] = "frappuccino",
		["Name"] = "Frappuccino",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["orangejuice"] = {
		["Index"] = "orangejuice",
		["Name"] = "Suco de Laranja",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["tangejuice"] = {
		["Index"] = "tangejuice",
		["Name"] = "Suco de Tangerina",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["grapejuice"] = {
		["Index"] = "grapejuice",
		["Name"] = "Suco de Uva",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,		
	},
	["strawberryjuice"] = {
		["Index"] = "strawberryjuice",
		["Name"] = "Suco de Morango",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["bananajuice"] = {
		["Index"] = "bananajuice",
		["Name"] = "Suco de Banana",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["acerolajuice"] = {
		["Index"] = "acerolajuice",
		["Name"] = "Suco de Acerola",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["passionjuice"] = {
		["Index"] = "passionjuice",
		["Name"] = "Suco de Maracujá",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["sal"] = {
		["Index"] = "sal",
		["Name"] = "Sal do Himalaia",
		["Type"] = "Comum",
		["Weight"] = 0.1,
	},
	["ketchup"] = {
		["Index"] = "ketchup",
		["Name"] = "Ketchup",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["cannedsoup"] = {
		["Index"] = "cannedsoup",
		["Name"] = "Sopa em Lata",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
	},
	["canofbeans"] = {
		["Index"] = "canofbeans",
		["Name"] = "Lata de Feijão",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
	},
	["meat"] = {
		["Index"] = "meat",
		["Name"] = "Carne Animal",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["meat2"] = {
		["Index"] = "meat2",
		["Name"] = "Carne de Soja",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["fishfillet"] = {
		["Index"] = "fishfillet",
		["Name"] = "Filé de Peixe",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["marshmallow"] = {
		["Index"] = "marshmallow",
		["Name"] = "Marshmallow",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.25,
		["Scape"] = true,
		["Max"] = 10,
	},
	["cookedfishfillet"] = {
		["Index"] = "cookedfishfillet",
		["Name"] = "Filé de Pescada com Fritas",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["cookedmeat"] = {
		["Index"] = "cookedmeat",
		["Name"] = "Carne Animal Cozida",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["hamburger"] = {
		["Index"] = "hamburger",
		["Name"] = "Big Mac",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.55,
		["Max"] = 10,
	},
	["hamburger2"] = {
		["Index"] = "hamburger2",
		["Name"] = "Big Tasty",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["onionrings"] = {
		["Index"] = "onionrings",
		["Name"] = "Anéis de Cebola",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 10,
	},
	["chickenfries"] = {
		["Index"] = "chickenfries",
		["Name"] = "Frango Frito",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["pizzamozzarella"] = {
		["Index"] = "pizzamozzarella",
		["Name"] = "Pizza de Muçarela",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 10,
	},
	["pizzamushroom"] = {
		["Index"] = "pizzamushroom",
		["Name"] = "Pizza de Cogumelo",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 3,
	},
	["pizzabanana"] = {
		["Index"] = "pizzabanana",
		["Name"] = "Pizza de Banana",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 3,
	},
	["pizzachocolate"] = {
		["Index"] = "pizzachocolate",
		["Name"] = "Pizza de Chocolate",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.75,
		["Scape"] = true,
		["Max"] = 3,
	},
	["calzone"] = {
		["Index"] = "calzone",
		["Name"] = "Calzone",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 3,
	},
	["hotdog"] = {
		["Index"] = "hotdog",
		["Name"] = "Hot-Dog",
		["Type"] = "Usável",
		["Durability"] = 5,
		["Weight"] = 0.45,
		["Max"] = 10,
	},
	["plate"] = {
		["Index"] = "plate",
		["Name"] = "Placa",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["lockpick"] = {
		["Index"] = "lockpick",
		["Name"] = "Chave de Alumínio",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.25,
	},
	["lockpick2"] = {
		["Index"] = "lockpick2",
		["Name"] = "Chave de Aluminio Policial",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.25,
	},
	["lockpickadv"] = {
		["Index"] = "lockpickadv",
		["Name"] = "Lockpick Ilegal",
		["Description"] = "Utilizada para roubar casas.",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 3,
		["Weight"] = 1.25,
	},
	["toolbox"] = {
		["Index"] = "toolbox",
		["Name"] = "Ferramentas Básicas",
		["Type"] = "Usável",
		["Weight"] = 2.25,
		["Max"] = 10,
	},
	["advtoolbox"] = {
		["Index"] = "toolbox",
		["Name"] = "Ferramentas Avançadas",
		["Type"] = "Usável",
		["Weight"] = 3.25,
		["Charges"] = 3,
		["Max"] = 2,
	},
	["notepad"] = {
		["Index"] = "notepad",
		["Name"] = "Bloco de Notas",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["tyres"] = {
		["Index"] = "tyres",
		["Name"] = "Pneu",
		["Type"] = "Usável",
		["Weight"] = 2.75,
		["Max"] = 4,
	},
	["cellphone"] = {
		["Index"] = "cellphone",
		["Name"] = "Celular",
		["Repair"] = "repairkit04",
		["Type"] = "Comum",
		["Durability"] = 7,
		["Weight"] = 0.75,
	},
	["scuba"] = {
		["Index"] = "scuba",
		["Name"] = "Roupa de Mergulho",
		["Type"] = "Usável",
		["Durability"] = 14,
		["Weight"] = 4.75,
	},
	["scuba2"] = {
		["Index"] = "scuba",
		["Name"] = "Roupa de Mergulho Profissional",
		["Type"] = "Usável",
		["Durability"] = 14,
		["Weight"] = 4.75,
	},
	["handcuff"] = {
		["Index"] = "handcuff",
		["Name"] = "Algemas",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 10,
		["Weight"] = 1.25,
	},
	["rope"] = {
		["Index"] = "rope",
		["Name"] = "Cordas",
		["Repair"] = "repairkit01",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 1.75,
	},
	["hood"] = {
		["Index"] = "hood",
		["Name"] = "Capuz",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["plastic"] = {
		["Index"] = "plastic",
		["Name"] = "Plástico",
		["Type"] = "Comum",
		["Weight"] = 0.080,
	},
	["glass"] = {
		["Index"] = "glass",
		["Name"] = "Vidro",
		["Type"] = "Comum",
		["Weight"] = 0.065,
	},
	["registro"] = {
		["Index"] = "registro",
		["Name"] = "Registro Agropecuário",
		["Description"] = "Obrigatório porta-lo durante qualquer atividade de pesca, caça ou agricultura.",
		["Type"] = "Comum",
		["Weight"] = 0.02,
		["Durability"] = 7
	},
	["bread"] = {
		["Index"] = "bread",
		["Name"] = "Pão",
		["Type"] = "Comum",
		["Weight"] = 0.1,
	},
	["moladearma"] = {
		["Index"] = "moladearma",
		["Name"] = "Mola para armamentos",
		["Type"] = "Comum",
		["Weight"] = 0.05,
	},
	["capsula"] = {
		["Index"] = "capsula",
		["Name"] = "Capsula Balística",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["projetil"] = {
		["Index"] = "projetil",
		["Name"] = "Projétil Balístico",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["rubber"] = {
		["Index"] = "rubber",
		["Name"] = "Borracha",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["copper"] = {
		["Index"] = "copper",
		["Name"] = "Cobre",
		["Type"] = "Comum",
		["Weight"] = 0.10,
	},
	["ritmoneury"] = {
		["Index"] = "ritmoneury",
		["Name"] = "Ritmoneury",
		["Type"] = "Usável",
		["Weight"] = 0.75,
		["Max"] = 5,
	},
	["sinkalmy"] = {
		["Index"] = "sinkalmy",
		["Name"] = "Sinkalmy",
		["Type"] = "Usável",
		["Weight"] = 0.75,
		["Max"] = 5,
	},
	["cigarette"] = {
		["Index"] = "cigarette",
		["Name"] = "Cigarro",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		["Max"] = 20,
	},
	["lighter"] = {
		["Index"] = "lighter",
		["Name"] = "Isqueiro",
		["Repair"] = "repairkit01",
		["Durability"] = 7,
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["vape"] = {
		["Index"] = "vape",
		["Name"] = "Vape",
		["Repair"] = "repairkit02",
		["Type"] = "Usável",
		["Durability"] = 14,
		["Weight"] = 0.75,
	},
	["dollars"] = {
		["Index"] = "dollars",
		["Name"] = "Reais",
		["Type"] = "Comum",
		["Weight"] = 0.0,
		['Block'] = true
	},
	["dollarz"] = {
		["Index"] = "dollarz",
		["Name"] = "Rolo de notas",
		["Description"] = "Recomendamos que não deposite em sua conta.",
		["Type"] = "Comum",
		["Weight"] = 0.0,
		['Block'] = true
	},
	["dollarx"] = {
		["Index"] = "dollarx",
		["Name"] = "Dinheiro marcado",
		["Description"] = "Proveniente de atos ilícitos.",
		["Type"] = "Comum",
		["Weight"] = 0.0,
		['Block'] = true
	},
	["battery"] = {
		["Index"] = "battery",
		["Name"] = "Pilhas",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["elastic"] = {
		["Index"] = "elastic",
		["Name"] = "Elástico",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["plasticbottle"] = {
		["Index"] = "plasticbottle",
		["Name"] = "Garrafa Plástica",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["glassbottle"] = {
		["Index"] = "glassbottle",
		["Name"] = "Garrafa de Vidro",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["reciclavel"] = {
		["Index"] = "reciclavel",
		["Name"] = "Material Reciclável",
		["Description"] = "Utilizado para troca na reciclagem.",
		["Type"] = "Comum",
		["Weight"] = 0.20,
	},
	["metalcan"] = {
		["Index"] = "metalcan",
		["Name"] = "Lata de Metal",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["chocolate"] = {
		["Index"] = "chocolate",
		["Name"] = "Chocolate",
		["Type"] = "Usável",
		["Weight"] = 0.15,
		["Scape"] = true,
		["Max"] = 10,
	},
	["nigirizushi"] = {
		["Index"] = "nigirizushi",
		["Name"] = "Nigirizushi",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.65,
		["Scape"] = true,
		["Max"] = 5,
		["Economy"] = 75
	},
	["sushi"] = {
		["Index"] = "sushi",
		["Name"] = "Sushi",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.65,
		["Scape"] = true,
		["Max"] = 5,
		["Economy"] = 75
	},

	["quiche"] = {
		["Index"] = "quiche",
		["Name"] = "Esfirra de frango",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 5,
		["Economy"] = 75
	},
	["redvelvet"] = {
		["Index"] = "redvelvet",
		["Name"] = "Bolo de Morango",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 5,
		["Economy"] = 75
	},
	["sorvete"] = {
		["Index"] = "sorvete",
		["Name"] = "Sorvete",
		["Type"] = "Usável",
		["Durability"] = 2,
		["Weight"] = 0.55,
		["Scape"] = true,
		["Max"] = 5,
		["Economy"] = 75
	},
	["sandwich"] = {
		["Index"] = "sandwich",
		["Name"] = "Sanduiche",
		["Type"] = "Usável",
		["Durability"] = 1,
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["rose"] = {
		["Index"] = "rose",
		["Name"] = "Rosa",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["teddy"] = {
		["Index"] = "teddy",
		["Name"] = "Teddy",
		["Type"] = "Usável",
		["Weight"] = 1.25,
	},
	["goldbar"] = {
		["Index"] = "goldbar",
		["Name"] = "Barra de Ouro",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["binoculars"] = {
		["Index"] = "binoculars",
		["Name"] = "Binóculos",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["camera"] = {
		["Index"] = "camera",
		["Name"] = "Câmera",
		["Type"] = "Usável",
		["Weight"] = 1.25,
	},
	["WEAPON_HATCHET"] = {
		["Index"] = "hatchet",
		["Name"] = "Machado",
		["Type"] = "Armamento",
		["Repair"] = "repairkit01",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["WEAPON_KNIFE"] = {
		["Index"] = "knife",
		["Name"] = "Faca",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["WEAPON_BAT"] = {
		["Index"] = "bat",
		["Name"] = "Bastão de Beisebol",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["PA"] = {
		["Index"] = "PA",
		["Name"] = "Pá",
		["Type"] = "Armamento",
		["Description"] = "Utilizada na agicultura",
		["Durability"] = 3,
		["Weight"] = 1.25,
	},
	["WEAPON_BATTLEAXE"] = {
		["Index"] = "battleaxe",
		["Name"] = "Machado de Batalha",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.75,
	},
	["WEAPON_DRILL"] = {
		["Index"] = "drill",
		["Name"] = "Drill",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 1,
		["Weight"] = 1.35,
	},
	["WEAPON_CROWBAR"] = {
		["Index"] = "crowbar",
		["Name"] = "Pé de Cabra",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.35,
	},
	["WEAPON_GOLFCLUB"] = {
		["Index"] = "golfclub",
		["Name"] = "Taco de Golf",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.65,
	},
	["WEAPON_HAMMER"] = {
		["Index"] = "hammer",
		["Name"] = "Martelo",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.45,
	},
	["WEAPON_MACHETE"] = {
		["Index"] = "machete",
		["Name"] = "Facão",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.35,
	},
	["WEAPON_POOLCUE"] = {
		["Index"] = "poolcue",
		["Name"] = "Taco de Sinuca",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.25,
	},
	["WEAPON_STONE_HATCHET"] = {
		["Index"] = "stonehatchet",
		["Name"] = "Tesoura",
		["Description"] = "Utilizada no pomar",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.55,
	},
	["suspensaoar"] = {
		["Index"] = "suspensaoar",
		["Name"] = "Kit Suspensão a ar",
		["Description"] = "Kit Suspensão a ar",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["kitneon"] = {
		["Index"] = "kitneon",
		["Name"] = "Kit módulo Neon",
		["Description"] = "Kit módulo Neon",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["kitxenon"] = {
		["Index"] = "kitxenon",
		["Name"] = "Kit módulo Xenon",
		["Description"] = "Kit módulo Xenon",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["kitcamber"] = {
		["Index"] = "kitcamber",
		["Name"] = "Kit módulo Camber",
		["Description"] = "Kit módulo Camber",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["kitoffset"] = {
		["Index"] = "kitoffset",
		["Name"] = "Kit módulo Offset",
		["Description"] = "Kit módulo Offset",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["escapamentoPop"] = {
		["Index"] = "escapamentoPop",
		["Name"] = "Escapamento Especial",
		["Description"] = "Escapamento Especial",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["fueltech"] = {
		["Index"] = "fueltech",
		["Name"] = "Fueltech",
		["Description"] = "Fueltech",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["westgate"] = {
		["Index"] = "westgate",
		["Name"] = "Westgate",
		["Description"] = "Westgate",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["purgador"] = {
		["Index"] = "purgador",
		["Name"] = "Purgador",
		["Description"] = "Purgador",
		["Type"] = "Usável",
		["Weight"] = 0.5,
	},
	["WEAPON_WRENCH"] = {
		["Index"] = "wrench",
		["Name"] = "Chave Inglesa",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 1,
		["Weight"] = 1.45,
	},
	["WEAPON_KNUCKLE"] = {
		["Index"] = "knuckle",
		["Name"] = "Soco Inglês",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_FLARE"] = {
		["Index"] = "flare",
		["Name"] = "Sinalizador",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_FLASHLIGHT"] = {
		["Index"] = "flashlight",
		["Name"] = "Lanterna",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_NIGHTSTICK"] = {
		["Index"] = "nightstick",
		["Name"] = "Cassetete",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_PISTOL"] = {
		["Index"] = "m1911",
		["Name"] = "M1911",
		["Repair"] = "repairkit02",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.05,
	},
	["WEAPON_PISTOL_MK2"] = {  --------- NOME DE SPAWN
		["Index"] = "fiveseven", ----- NOME DA IMAGEM CHAMADA NO PASTA IMAGE
		["Name"] = "FN Five Seven",---- NOME FANTASIA 
		["Repair"] = "repairkit02",
		["Type"] = "Armamento",  -----------
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.05,
	},
	["TOKEN_PISTOL50"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Desert Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_PISTOL_MK2"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "FiveSeven Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_PISTOL"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "M1911 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_SNSPISTOL"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "AMT 380 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_HEAVYPISTOL"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "FX45 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_APPISTOL"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Glock Rajada Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_TAURUSRT82"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "PT 82 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_FAMAE"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Famae Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_REVOLVER"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Magnum 44 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_GUSENBERG"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Thompson Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_ASSAULTSMG"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Steyr AUG Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_SMG_MK2"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Evo-3 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_ASSAULTRIFLE"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "AK-103 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_ASSAULTRIFLE_MK2"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "AK-74 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_AR15PRETO"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "AR15 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_SPECIALCARBINE_MK2"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "Sig Sauer 556 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_COMPACTRIFLE"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "AK Compact Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["TOKEN_FNFAL"] = { 
		["Index"] = "weaponbox", 
		["Name"] = "FN L1A1 Lacrada",
		["Type"] = "Token",  
		["Weight"] = 1.05,
	},
	["WEAPON_LR25"] = {
		["Index"] = "mk18b",
		["Name"] = "LR25",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_DD14_B"] = {
		["Index"] = "mk18b",
		["Name"] = "DD14",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_DD11_C"] = {
		["Index"] = "mk18b",
		["Name"] = "DD11 GER",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_COMPACTRIFLE"] = {
		["Index"] = "akcompact",
		["Name"] = "AK Compact",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.05,
	},
	["WEAPON_APPISTOL"] = {
		["Index"] = "kochvp9",
		["Name"] = "Glock Rajada",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.05,
	},
	["WEAPON_HEAVYPISTOL"] = {
		["Index"] = "atifx45",
		["Name"] = "FX45",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_MACHINEPISTOL"] = {
		["Index"] = "tec9",
		["Name"] = "Tec-9",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Repair"] = "repairkit03",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_MICROSMG"] = {
		["Index"] = "uzi",
		["Name"] = "Uzi",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Repair"] = "repairkit03",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_NAILGUN"] = {
		["Index"] = "nailgun",
		["Name"] = "Arma de Prego",
		["Repair"] = "repairkit01",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_NAIL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = false,
		["Weight"] = 1.00,
	},
	["WEAPON_MINISMG"] = {
		["Index"] = "skorpionv61",
		["Name"] = "Skorpion V61",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_SNSPISTOL"] = {
		["Index"] = "amt380",
		["Name"] = "AMT 380",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_SNSPISTOL_MK2"] = {
		["Index"] = "hkp7m10",
		["Name"] = "HK P7M10",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_VINTAGEPISTOL"] = {
		["Index"] = "m1922",
		["Name"] = "Ruger Mark IV",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_PISTOL50"] = {
		["Index"] = "desert",
		["Name"] = "Desert Eagle",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_TAURUSRT82"] = {
		["Index"] = "magnum",
		["Name"] = "Revolver Taurus PT82",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_357P"] = {
		["Index"] = "magnum",
		["Name"] = "Revolver 357",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_REVOLVER"] = {
		["Index"] = "magnum",
		["Name"] = "Magnum 44",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_REVOLVER_MK2"] = {
		["Index"] = "magnum",
		["Name"] = "Magnum 44",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_DDM4"] = {
		["Index"] = "ddm4",
		["Name"] = "Fuzil Civil",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_FNSCAR"] = {
		["Index"] = "g36c",
		["Name"] = "Fuzil Rota",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_MK18T"] = {
		["Index"] = "mk18t",
		["Name"] = "MK18T",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_MK18"] = {
		["Index"] = "mk18b",
		["Name"] = "MK18 GARRA",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_MK18B"] = {
		["Index"] = "mk18b",
		["Name"] = "MK18B GER",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_COMBATPISTOL"] = {
		["Index"] = "glock",
		["Name"] = "Glock",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_M15"] = {
		["Index"] = "m4a1",
		["Name"] = "M15",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_M4A"] = {
		["Index"] = "m4a4",
		["Name"] = "M4A",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SCARH"] = {
		["Index"] = "m4a4",
		["Name"] = "SCAR H",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_ARAD"] = {
		["Index"] = "m4a4",
		["Name"] = "Arad GER",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_ARADGARRA"] = {
		["Index"] = "m4a4",
		["Name"] = "Arad GARRA",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SCARL"] = {
		["Index"] = "m4a4",
		["Name"] = "SCAR L",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_PARAFAL"] = {
		["Index"] = "parafal",
		["Name"] = "PARA-FAL M964A1",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_FNFAL"] = {
		["Index"] = "fnfal",
		["Name"] = "FN L1A1",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_SPECIALCARBINE_LUXE"] = {
		["Index"] = "parafal",
		["Name"] = "Parafal Serrado",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_AR15PRETO"] = {
		["Index"] = "ar15preto",
		["Name"] = "AR 15",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_AKCROMADO"] = {
		["Index"] = "ak47m",
		["Name"] = "AkCromado",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_MG"] = {
		["Index"] = "m110",
		["Name"] = ".50",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 8.00,
	},
	["WEAPON_MARKSMANRIFLE"] = {
		["Index"] = "m110",
		["Name"] = "Fuzil Camuflado",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_DOZEBORRACHA"] = {
		["Index"] = "mossberg590",
		["Name"] = "Doze de Borracha",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SHOTGUN_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_COLTXM177"] = {
		["Index"] = "coltxm177",
		["Name"] = "Colt XM177",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_GLOCKBEGE"] = {
		["Index"] = "Glock Civil",
		["Name"] = "Glock Civil",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_P88"] = {
		["Index"] = "glock",
		["Name"] = "Walther P88",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_PT92"] = {
		["Index"] = "glock",
		["Name"] = "PT92",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_PT247"] = {
		["Index"] = "glock",
		["Name"] = "Taurus 247",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_M17"] = {
		["Index"] = "glock",
		["Name"] = "M17",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_PT100"] = {
		["Index"] = "glock",
		["Name"] = "Taurus 100",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PISTOL_POLICE",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_CARBINERIFLE"] = {
		["Index"] = "m4a1",
		["Name"] = "IMBEL 762 IA2",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_IA2"] = {
		["Index"] = "m4a1",
		["Name"] = "IMBEL 762 556",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_CHK416"] = {
		["Index"] = "m4a4",
		["Name"] = "CHK416",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_AR10T"] = {
		["Index"] = "m4a4",
		["Name"] = "AR10T",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_LBRS"] = {
		["Index"] = "m4a4",
		["Name"] = "LBRS",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_M4PF"] = {
		["Index"] = "m4a4",
		["Name"] = "M4 PF",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_EFTPM"] = {
		["Index"] = "m4a4",
		["Name"] = "EFT PM",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_IA2PM"] = {
		["Index"] = "m4a4",
		["Name"] = "IA2 PM",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_CARBINERIFLE_MK2"] = {
		["Index"] = "m4a4",
		["Name"] = "M4A4",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_ADVANCEDRIFLE"] = {
		["Index"] = "tar21",
		["Name"] = "Tar-21",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_BULLPUPRIFLE"] = {
		["Index"] = "qbz95",
		["Name"] = "QBZ-95",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_BULLPUPRIFLE_MK2"] = {
		["Index"] = "l85",
		["Name"] = "L85",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SPECIALCARBINE"] = {
		["Index"] = "g36c",
		["Name"] = "Fn-Scar",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SPECIALCARBINE_MK2"] = {
		["Index"] = "sigsauer556",
		["Name"] = "Sig Sauer 556",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_FM1_BENELLIM4"] = {
		["Index"] = "mossberg590",
		["Name"] = "Benelli M4",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SHOTGUN_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_PUMPSHOTGUN"] = {
		["Index"] = "mossberg590",
		["Name"] = "Mossberg 590",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SHOTGUN_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_PUMPSHOTGUN_MK2"] = {
		["Index"] = "mossberg590a1",
		["Name"] = "Mossberg 590A1",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SHOTGUN_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_MUSKET"] = {
		["Index"] = "winchester",
		["Name"] = "Winchester 1892",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_MUSKET_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SAWNOFFSHOTGUN"] = {
		["Index"] = "mossberg500",
		["Name"] = "Mossberg 500",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SHOTGUN_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_APC40"] = {
		["Index"] = "mp5",
		["Name"] = "B&T APC .40",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_FAMAE"] = {
		["Index"] = "mp5",
		["Name"] = "Famae",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_BETSUB"] = {
		["Index"] = "mp5",
		["Name"] = "Bet",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SMG"] = {
		["Index"] = "mp5",
		["Name"] = "MP5",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_SMG_MK2"] = {
		["Index"] = "evo3",
		["Name"] = "Evo-3",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Vehicle"] = true,
		["Weight"] = 1.00,
	},
	["WEAPON_ASSAULTRIFLE"] = {
		["Index"] = "ak103",
		["Name"] = "AK-103",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_ASSAULTRIFLE_MK2"] = {
		["Index"] = "ak74",
		["Name"] = "AK-74",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_ASSAULTSMG"] = {
		["Index"] = "steyraug",
		["Name"] = "Steyr AUG",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RIFLE_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_GUSENBERG"] = {
		["Index"] = "thompson",
		["Name"] = "Thompson",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SMG_AMMO",
		["Durability"] = 7,
		["Weight"] = 1.00,
	},
	["WEAPON_PETROLCAN"] = {
		["Index"] = "gallon",
		["Name"] = "Galão",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_PETROLCAN_AMMO",
		["Weight"] = 1.00,
	},
	["GADGET_PARACHUTE"] = {
		["Index"] = "parachute",
		["Name"] = "Paraquedas",
		["Type"] = "Usável",
		["Weight"] = 1.00,
	},
	["WEAPON_STUNGUN"] = {
		["Index"] = "stungun",
		["Name"] = "Tazer",
		["Type"] = "Armamento",
		["Durability"] = 7,
		["Weight"] = 0.1,
	},
	["WEAPON_NAIL_AMMO"] = {
		["Index"] = "nails",
		["Name"] = "Pregos",
		["Type"] = "Munição",
		["Weight"] = 0.1,
	},
	["WEAPON_SNIPERRIFLE"] = {
		["Index"] = "sniperrifle",
		["Name"] = "Sniper",
		["Repair"] = "repairkit03",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_SNIPER_AMMO",
		["Durability"] = 1,
		["Weight"] = 1.0,
	},
	-- ["WEAPON_HEAVYSNIPER"] = {
	-- 	["Index"] = "heavysniper",
	-- 	["Name"] = "Sniper Pesada",
	-- 	["Repair"] = "repairkit03",
	-- 	["Type"] = "Armamento",
	-- 	["Ammo"] = "WEAPON_SNIPER_AMMO",
	-- 	["Durability"] = 7,
	-- 	["Weight"] = 1.0,
	-- },
	-- ["WEAPON_SNIPER_AMMO"] = {
	-- 	["Index"] = "sniperammo",
	-- 	["Name"] = "Munição de Sniper",
	-- 	["Type"] = "Munição",
	-- 	["Weight"] = 0.1,
	-- },
	["WEAPON_PISTOL_AMMO"] = {
		["Index"] = "pistolammo",
		["Name"] = "Munição de Pistola",
		["Type"] = "Munição",
		["Weight"] = 0.1,
	},
	["WEAPON_PISTOL_POLICE"] = {
		["Index"] = "pistolammo",
		["Name"] = "Munição de Pistola Policial",
		["Type"] = "Munição",
		["Weight"] = 0.1,
	},
	["WEAPON_SMG_AMMO"] = {
		["Index"] = "smgammo",
		["Name"] = "Munição de Sub",
		["Type"] = "Munição",
		["Weight"] = 0.1,
	},
	["WEAPON_RIFLE_AMMO"] = {
		["Index"] = "rifleammo",
		["Name"] = "Munição de Rifle",
		["Type"] = "Munição",
		["Weight"] = 0.1,
	},
	["WEAPON_SHOTGUN_AMMO"] = {
		["Index"] = "shotgunammo",
		["Name"] = "Munição de Escopeta",
		["Type"] = "Munição",
		["Weight"] = 0.5,
	},
	["WEAPON_MUSKET_AMMO"] = {
		["Index"] = "musketammo",
		["Name"] = "Munição de Mosquete",
		["Type"] = "Munição",
		["Weight"] = 0.5,
	},
	["WEAPON_PETROLCAN_AMMO"] = {
		["Index"] = "fuel",
		["Name"] = "Combustível",
		["Type"] = "Munição",
		["Weight"] = 0.0,
	},
	["WEAPON_BRICK"] = {
		["Index"] = "brick",
		["Name"] = "Tijolo",
		["Type"] = "Throwing",
		["Vehicle"] = true,
		["Weight"] = 0.5,
	},
	["WEAPON_SNOWBALL"] = {
		["Index"] = "snowball",
		["Name"] = "Bola de Neve",
		["Type"] = "Throwing",
		["Vehicle"] = true,
		["Weight"] = 0.5,
	},
	["WEAPON_SHOES"] = {
		["Index"] = "shoes",
		["Name"] = "Tênis",
		["Type"] = "Throwing",
		["Vehicle"] = true,
		["Weight"] = 0.5,
	},
	["WEAPON_MOLOTOV"] = {
		["Index"] = "molotov",
		["Name"] = "Coquetel Molotov",
		["Type"] = "Throwing",
		["Vehicle"] = true,
		["Weight"] = 0.2,
		["Max"] = 1
	},
	["WEAPON_SMOKEGRENADE"] = {
		["Index"] = "smokegrenade",
		["Name"] = "Granada de Fumaça",
		["Type"] = "Throwing",
		["Vehicle"] = true,
		["Weight"] = 0.5,
		["Max"] = 1
	},
	["pager"] = {
		["Index"] = "pager",
		["Name"] = "Pager",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["firecracker"] = {
		["Index"] = "firecracker",
		["Name"] = "Fogos de Artificio",
		["Description"] = "Traga uma multidão com esses lindos fogos de artifício.",
		["Type"] = "Usável",
		["Weight"] = 2.25,
	},
	["analgesic"] = {
		["Index"] = "analgesic",
		["Name"] = "Analgésico",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 5,
	},
	["drogazil"] = {
		["Index"] = "analgesic",
		["Name"] = "Droga-zil",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 5,
	},
	["oxy"] = {
		["Index"] = "analgesic",
		["Name"] = "Oxy",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 5,
	},
	["gauze"] = {
		["Index"] = "gauze",
		["Name"] = "Gaze",
		["Type"] = "Usável",
		["Weight"] = 0.25,
		["Max"] = 10,
	},
	["gsrkit"] = {
		["Index"] = "gsrkit",
		["Name"] = "Kit Residual",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["gdtkit"] = {
		["Index"] = "gdtkit",
		["Name"] = "Kit Químico",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["coal"] = {
		["Index"] = "coal",
		["Name"] = "Carvão",
		["Type"] = "Comum",
		["Weight"] = 0.95,
	},
	["sulfur"] = {
		["Index"] = "sulfur",
		["Name"] = "Enxofre",
		["Description"] = "Isso fede muito!",
		["Type"] = "Comum",
		["Weight"] = 0.95,
	},
	["polvora"] = {
		["Index"] = "polvora",
		["Name"] = "Pólvora",
		["Description"] = "Altamente inflamável!",
		["Type"] = "Comum",
		["Weight"] = 0.1,
	},
	["emerald"] = {
		["Index"] = "emerald",
		["Name"] = "Esmeralda",
		["Type"] = "Comum",
		["Weight"] = 0.95,
	},
	["diamond"] = {
		["Index"] = "diamond",
		["Name"] = "Diamante",
		["Type"] = "Comum",
		["Weight"] = 0.95,
	},
	["ruby"] = {
		["Index"] = "ruby",
		["Name"] = "Rubi",
		["Type"] = "Comum",
		["Weight"] = 0.85,
	},
	["sapphire"] = {
		["Index"] = "sapphire",
		["Name"] = "Safira",
		["Type"] = "Comum",
		["Weight"] = 0.85,
	},
	["amethyst"] = {
		["Index"] = "amethyst",
		["Name"] = "Ametista",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["amber"] = {
		["Index"] = "amber",
		["Name"] = "Âmbar",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["turquoise"] = {
		["Index"] = "turquoise",
		["Name"] = "Turquesa",
		["Type"] = "Comum",
		["Weight"] = 0.65,
	},
	["keyboard"] = {
		["Index"] = "keyboard",
		["Name"] = "Teclado",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["mouse"] = {
		["Index"] = "mouse",
		["Name"] = "Mouse",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["smarthwatch"] = {
		["Index"] = "smarthwatch",
		["Name"] = "Smarth Watch",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["silverring"] = {
		["Index"] = "silverring",
		["Name"] = "Anel de Prata",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["adrenaline"] = {
        ["Index"] = "adrenaline",
        ["Name"] = "Adrenalina",
        ["Type"] = "Usável",
        ["Weight"] = 0.35,
		["Max"] = 1,
    },
	["phone"] = {
		["Index"] = "phone",
		["Name"] = "Fone de ouvido Bluetooth",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["smarthphone"] = {
		["Index"] = "smarthphone",
		["Name"] = "Galáxia S15 Quebrado",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["brincodeouro"] = {
		["Index"] = "brincodeouro",
		["Name"] = "Brincos de ouro",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["correntedeouro"] = {
		["Index"] = "correntedeouro",
		["Name"] = "Corrente de Ouro",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["goldring"] = {
		["Index"] = "goldring",
		["Name"] = "Anel de Ouro",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["silvercoin"] = {
		["Index"] = "silvercoin",
		["Name"] = "Moeda de Prata",
		["Type"] = "Usável",
		["Weight"] = 0.05,
	},
	["goldcoin"] = {
		["Index"] = "goldcoin",
		["Name"] = "Moeda de Ouro",
		["Type"] = "Usável",
		["Weight"] = 0.05,
	},
	["watch"] = {
		["Index"] = "watch",
		["Name"] = "Relógio",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["playstation"] = {
		["Index"] = "playstation",
		["Name"] = "Playstation",
		["Type"] = "Comum",
		["Weight"] = 1.25,
	},
	["xbox"] = {
		["Index"] = "xbox",
		["Name"] = "Xbox",
		["Type"] = "Comum",
		["Weight"] = 1.25,
	},
	["inscricao"] = {
		["Index"] = "inscricao",
		["Name"] = "Ticket de inscrição para evento",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["centraldecontrole"] = {
		["Index"] = "centralveicular",
		["Name"] = "central veicular",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["recibo"] = {
		["Index"] = "recibo",
		["Name"] = "recibo",
		["Type"] = "Comum",
		["Weight"] = 0.1,
	},
	["bracelet"] = {
		["Index"] = "bracelet",
		["Name"] = "Bracelete",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["bateria"] = {
		["Index"] = "bateria",
		["Name"] = "bateria",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["spray01"] = {
		["Index"] = "spray01",
		["Name"] = "Desodorante 24hrs",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["spray02"] = {
		["Index"] = "spray02",
		["Name"] = "Antisséptico",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["spray03"] = {
		["Index"] = "spray03",
		["Name"] = "Desodorante 48hrs",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["spray04"] = {
		["Index"] = "spray04",
		["Name"] = "Desodorante 72hrs",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["dices"] = {
		["Index"] = "dices",
		["Name"] = "Dados",
		["Type"] = "Usável",
		["Weight"] = 0.35,
	},
	["dish"] = {
		["Index"] = "dish",
		["Name"] = "Prato",
		["Type"] = "Comum",
		["Weight"] = 0.55,
	},
	["oxidonitroso"] = {
		["Index"] = "oxidonitroso",
		["Name"] = "Carga de óxido nitroso",
		["Type"] = "Usável",
		["Weight"] = 0.55,
	},
	["fan"] = {
		["Index"] = "fan",
		["Name"] = "Ventilador",
		["Type"] = "Comum",
		["Weight"] = 1.15,
	},
	["smartphone"] = {
		["Index"] = "smartphone",
		["Name"] = "smartphone",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["blender"] = {
		["Index"] = "blender",
		["Name"] = "Liquidificador",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["switch"] = {
		["Index"] = "switch",
		["Name"] = "Interruptor",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["horseshoe"] = {
		["Index"] = "horseshoe",
		["Name"] = "Ferradura",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["brush"] = {
		["Index"] = "brush",
		["Name"] = "Escova",
		["Type"] = "Comum",
		["Weight"] = 0.25,
	},
	["pendrive"] = {
		["Index"] = "pendrive",
		["Name"] = "pendrive",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	["floppy"] = {
		["Index"] = "floppy",
		["Name"] = "Disquete",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	["cup"] = {
		["Index"] = "cup",
		["Name"] = "Cálice",
		["Type"] = "Comum",
		["Weight"] = 0.45,
	},
	["deck"] = {
		["Index"] = "deck",
		["Name"] = "Baralho",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["eraser"] = {
		["Index"] = "eraser",
		["Name"] = "Apagador",
		["Type"] = "Comum",
		["Weight"] = 0.15,
	},
	["pliers"] = {
		["Index"] = "pliers",
		["Name"] = "Alicate",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["lampshade"] = {
		["Index"] = "lampshade",
		["Name"] = "Abajur",
		["Type"] = "Comum",
		["Weight"] = 0.75,
	},
	["soap"] = {
		["Index"] = "soap",
		["Name"] = "Sabonete",
		["Type"] = "Usável",
		["Weight"] = 0.25,
	},
	["slipper"] = {
		["Index"] = "slipper",
		["Name"] = "Chinelo",
		["Type"] = "Comum",
		["Weight"] = 0.35,
	},
	["pendrive2"] = {
		["Index"] = "pendrive2",
		["Name"] = "Pendrive com Malware",
		["Type"] = "Usável",
		["Weight"] = 0.75,
	},
	["autorizacao"] = {
		["Index"] = "autorizacao",
		["Name"] = "Autorizaçao de trabalho",
		["Type"] = "Usável",
		["Description"] = "Certificado de autorização de trafego livre entre sul e norte para trabalho, o mesmo deve conter veiculo de trabalho e uniforme. VALIDO APENAS PARA TRABALHOS SEM SETAGEM.",
		["Charges"] = 2,
		["Weight"] = 0.1,
	},
	["vazo"] = {
		["Index"] = "vazo",
		["Name"] = "Vaso para colocar plantas",
		["Type"] = "Comum",
		["Weight"] = 1.500
	},
	["terra"] = {
		["Index"] = "terra",
		["Name"] = "Pacote de terra com fertilizante",
		["Type"] = "Comum",
		["Weight"] = 3.000
	},
	["dryweedleaf"] = {
		["Index"] = "dryweedleaf",
		["Name"] = "Flor de Cannabis Seca",
		["Type"] = "Comum",
		["Weight"] = 0.30
	},
	["racaosilvestre"] = {
		["Index"] = "racaosilvestre",
		["Name"] = "Ração Silvestre",
		["Description"] = "Raçao ultilizada para atrair o animal, Usável no ponto marcado no mapa.",
		["Type"] = "Usável",
		["Weight"] = 0.1,
	},
	["WEAPON_RPG_AMMO"] = {
		["Index"] = "rpg_ammo",
		["Name"] = "Munição de RPG",
		["Type"] = "Munição",
		["Weight"] = 0.045,
	},
	["WEAPON_RPG"] = {
		["Index"] = "weapon_rpg",
		["Name"] = "RPG Launcher",
		["Type"] = "Armamento",
		["Ammo"] = "WEAPON_RPG_AMMO",
		["Durability"] = 21,
		["Vehicle"] = true,
		["Weight"] = 5.25,
	},
	["slotgaragem"] = {
		["Index"] = "slotgaragem",
		["Name"] = "+1 Vaga de Garagem",
		["Description"] = "Adiciona uma vaga em sua garagem.",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		['Block'] = true
	},
	["chip"] = {
		["Index"] = "chip",
		["Name"] = "Chip Telefônico",
		["Type"] = "Usável",
		["Weight"] = 0.1,
		['Block'] = true
	},
	["pistolporte"] = {
		["Index"] = "pistolporte",
		["Name"] = "Pistola Lacrada",
		["Type"] = "Usável",
		["Weight"] = 1.0
	},
	["pistolporte2"] = {
		["Index"] = "pistolporte",
		["Name"] = "Revolver Lacrada",
		["Type"] = "Usável",
		["Weight"] = 1.0
	},
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMBODY
-----------------------------------------------------------------------------------------------------------------------------------------
function itemBody(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] then
		return List[Item]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMINDEX
-----------------------------------------------------------------------------------------------------------------------------------------
function itemIndex(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Index"] then
		return List[Item]["Index"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMNAME
-----------------------------------------------------------------------------------------------------------------------------------------
function itemName(Item)
	if not Item then return end
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Name"] then
		return List[Item]["Name"]
	end

	return "Deletado"
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMTYPE
-----------------------------------------------------------------------------------------------------------------------------------------
function itemType(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Type"] then
		return List[Item]["Type"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMAMMO
-----------------------------------------------------------------------------------------------------------------------------------------
function itemAmmo(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Ammo"] then
		return List[Item]["Ammo"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMVEHICLE
-----------------------------------------------------------------------------------------------------------------------------------------
function itemVehicle(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Vehicle"] then
		return List[Item]["Vehicle"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMWEIGHT
-----------------------------------------------------------------------------------------------------------------------------------------
function itemWeight(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Weight"] then
		return List[Item]["Weight"] + 0.0
	end

	return 0.0
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMMAXAMOUNT
-----------------------------------------------------------------------------------------------------------------------------------------
function itemMaxAmount(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Max"] then
		return List[Item]["Max"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMSCAPE
-----------------------------------------------------------------------------------------------------------------------------------------
function itemScape(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Scape"] then
		return List[Item]["Scape"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMDESCRIPTION
-----------------------------------------------------------------------------------------------------------------------------------------
function itemDescription(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Description"] then
		return List[Item]["Description"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMDURABILITY
-----------------------------------------------------------------------------------------------------------------------------------------
function itemDurability(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Durability"] then
		return List[Item]["Durability"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMCHARGES
-----------------------------------------------------------------------------------------------------------------------------------------
function itemCharges(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Charges"] then
		return List[Item]["Charges"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMECONOMY
-----------------------------------------------------------------------------------------------------------------------------------------
function itemEconomy(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Economy"] then
		return List[Item]["Economy"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMBLOCK
-----------------------------------------------------------------------------------------------------------------------------------------
function itemBlock(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Block"] then
		return List[Item]["Block"]
	end

	return false
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- ITEMREPAIR
-----------------------------------------------------------------------------------------------------------------------------------------
function itemRepair(Item)
	local Split = splitString(Item,"-")
	local Item = Split[1]

	if List[Item] and List[Item]["Repair"] then
		return List[Item]["Repair"]
	end

	return false
end