isDuplicity = IsDuplicityVersion()

if not isDuplicity then 
    local Tunnel = module("vrp","lib/Tunnel")
    local Proxy = module("vrp","lib/Proxy")
    vRP = Proxy.getInterface("vRP")
    vRPS = Tunnel.getInterface("vRP")
    Srr = {}
    Tunnel.bindInterface(GetCurrentResourceName(),Srr)
    vSERVER = Tunnel.getInterface(GetCurrentResourceName())
else
    local Tunnel = module("vrp","lib/Tunnel")
    local Proxy = module("vrp","lib/Proxy")
    vRP = Proxy.getInterface("vRP")
    vRPC = Tunnel.getInterface("vRP")
    Srr = {}
    Tunnel.bindInterface(GetCurrentResourceName(),Srr)
    vCLIENT = Tunnel.getInterface(GetCurrentResourceName())
end

Config = {
    ["Streets"] = {
        ["Paleto Boulevard"] = "Av. Senador Feijó",
        ["Pyrite Avenue"] = "R. Taubaté",
        ["Cascabel Avenue"] = "R. Braz Cuba",
        ["Procopio Drive"] = "Av. Afonso Pena",
        ["Duluoz Avenue"] = "R. Maranhão",
        ["Great Ocean Highway"] = "Rod. Anchieta",
        ["Procopio Promenade"] = "Av. Nossa senhora de Fátima",
        ["Cassidy Trail"] = "Caminho dos Pilões",
        ["North Calafia Way"] = "Estrada Velha de Santos",
        ["Seaview Road"] = "Av. Prudente de Morais",
        ["Grapeseed Main Street"] = "Av. Arnaldo Salles de Oliveira",
        ["Joad Lane"] = "Av. Sete de Setembro",
        ["O'Neil Way"] = "R. Campos Salles",
        ["Union Road"] = "R. Ruí Barbosa",
        ["Grapeseed Avenue"] = "R. Sebastião Luiz",
        ["Senora Freeway"] = "Rod. Dos Bandeirantes",
    
        ["East Joshua Road"] = "Av. Monteiro Lobato",
        ["Joshua Road"] = "Av. Monteiro Lobato", 
        ["Chianski Passage"] = "Av. Jaguari",
        ["Alhambra Drive"] = "R. Cachoeira",
        ["Marina Drive"] = "R. Emilio Ribas",
        ["Algonquin Boulevard"] = "Av. Guarulhos",
        ["Zancudo Avenue"] = "Av. julío Prestes",
        ["Mountain View Drive"] = "Av. Salgado Filho",
        ["Cholla Springs Avenue"] = "R. Dom Pedro II",
        ["Armadillo Avenue"] = "R. Oscar Lima",
        ["Niland Avenue"] = "R. Criciuma",
        ["Panorama Drive"] = "Av. Dr. Assis Ribeiro",
        ["Cat-Claw Avenue"] = "R. Gonçalves Dias",
        ["Smoke Tree Road"] = "R. Esmeralda",
        ["Nowhere Road"] = "Viela União",
        ["Route 68"] = "Rod. Transbasiliana",
        ["Calafia Road"] = "R. Orlando Segala",
        ["Route 68 Approach"] = "Monteiro Lobato / Transbasiliana",
        ["Catfish View"] = "R. Sebastião Luiz",
        ["Lorita Avenue"] = "R. das Rosas",
        ["Lesbos Lane"] = "R. Quinze",
        ["Meringue Lane"] = "R. Oito",
        ["Cholla Road"] = "R. Xingu",
    
        ["Zancudo Grande Valley"] = "Av. Francisco Glicério",
        ["Fort Zancudo Approach Road"] = "Terminal A / Aeroporto Viracopos",
        ["Zancudo Barranca"] = "R. Araçatuba",
        ["Barbareno Road"] = "R. Paranavai",                
        ["Ineseno Road"] = "R. Assembléia",                
        ["Banham Canyon Drive"] = "R. Luigi Batistini",     
        ["Buen Vino Road"] = "R. Serra do Pilar",           
        ["Galileo Road"] = "R. Fazendinha",
        ["Mount Vinewood Drive"] = "Av. Francisco Glicério",
        ["Edwood Way"] = "R. Manuel Borba",
        ["Strangeways Drive"] = "R. Cordeiro Galvão",
        ["Zancudo Road"] = "Av. Conselheiro Carrão",
    
        ["Senora Road"] = "Av. Senador Teotônio Vilela",
        ["Vinewood Boulevard"] = "Av. Paulista",
        ["Eclipse Boulevard"] = "Av. Paulista",
        ["Alta Street"] = "Av. dos Estados",
        ["Vespucci Boulevard"] = "Av. 23 de Maio",
        ["El Rancho Boulevard"] = "Av. Jacú Pêssego",
        ["Carson Avenue"] = "Av. Sapopemba",
        ["Innocence Boulevard"] = "Av. Aricanduva",
        ["Baytree Canyon Road"] = "Av. Marechal Tito",
        ["Marlowe Drive"] = " Alameda Campinas",
        ["Tongva Drive"] = "Rod. Anhaguera",          
        ["North Rockford Drive"] = "Av. Brig Faria Lima",
        ["South Rockford Drive"] = "Av. Brig Faria Lima",
        ["Milton Road"] = "Av. Canadá",
        ["North Sheldon Avenue"] = "Av. Europa",
        ["West Galileo Avenue"] = "Av. Ucrânia",
        ["East Galileo Avenue"] = "R. Tanzânia",
        ["Mount Haan Road"] = "R. Raul Tabajara",
        ["Vinewood Park Drive"] = "R. Roger Chaffee",
        ["Fenwell Place"] = "R. João Adolfo",
        ["Meteor Street"] = "R. da Consolação",
        ["Elgin Avenue"] = "Av. 13 de Maio",
        ["Mirror Park Boulevard"] = "Av. Jacú-Pessêgo",
        ["York Street"] = "R. São Fortunato",
        ["San Andreas Avenue"] = "Av. 9 de Julho",
        ["Hawick Avenue"] = "Av. Atlântica",
        ["Buccaneer Way"] = "Av. Salim Farah Maluf / Porto",
        ["Popular Street"] = "Av. Salim Farah Maluf",
        ["Palomino Freeway"] = "Rod. Ayrton Senna",
        ["Olympic Freeway"] = "Rod. Ayrton Senna",
        ["Los Santos Freeway"] = "Rod. Dos Bandeirantes",
        ["Strawberry Avenue"] = "Av. Interlagos",
        ["Integrity Way"] = "R. Brig. Galvão",
        ["Sinner Street"] = "R. Barra Funda",
        ["Adam's Apple Boulevard"] = "Alameda Eduardo Prado",
        ["Little Bighorn Avenue"] = "Av. Juscelino Kubitschek",
        ["Sinners Passage"] = "R. Boa Vista",
        ["Power Street"] = "Alameda Rocha Azevedo",
        ["Low Power Street"] = "Av. Francisco Matarazzo",
        ["Peaceful Street"] = "R. São Paulo",
        ["Davis Avenue"] = "Av. Santo Amaro",
        ["Macdonald Street"] = "R. Amador Bueno",
        ["Brouge Avenue"] = "R. Borba Gato",
        ["Covenant Avenue"] = "R. Min. Guimarães",
        ["Roy Lowenstein Boulevard"] = "Av. Giovanni Gronchi",
        ["Jamestown Street"] = "R. João Alfredo",
        ["Dutch London Street"] = "Av. Pedro Bueno",
        ["New Empire Way"] = "Aeroporto de Congonhas - CGH",
        ["La Puerta Freeway"] = "Marginal Pinheiros",
        ["Elysian Fields Freeway"] = "Marginal Pinheiros",
        ["Del Perro Freeway"] = "Marginal Tiête",
        ["Occupation Avenue"] = "Av. Angelica",
        ["Boulevard Del Perro"] = "Av. Atlântica",
        ["Las Lagunas Boulevard"] = "Av. Pacaembu",
        ["West Eclipse Boulevard"] = "Av. Autodromo",
        ["Palomino Avenue"] = "Av. Washington Luís",
        ["Dorset Drive"] = "Av. Rio Branco",
        ["Bay City Avenue"] = "Av. Guarapiranga",
        ["Prosperity Street"] = "R. dos Pinheiros",
        ["Red Desert Avenue"] = "Av. Berrini",
        ["Marathon Avenue"] = "R. Cantareira",
        ["Heritage Way"] = "R. São Vicente",
        ["Movie Star Way"] = "Av. Sumaré",
        ["South Boulevard Del Perro"] = "Av. Costa Rica",
        ["Portola Drive"] = "Av. São João",
        ["Carcer Way"] = "Av. Ipiranga",
        ["Abe Milton Parkway"] = "Av. Costa Rica",
        ["San Vitus Boulevard"] = "Av. Casper Libero",
        ["Morningwood Boulevard"] = "Av. Cap. Gustavo Sagat",
        ["Greenwich Place"] = "R. São Judas",
        ["Liberty Street"] = "R. Paris",
        ["Perth Street"] = "R. 15",
        ["Alta Place"] = "R. Mauá",
        ["Laguna Place"] = "R. Barão",
        ["Hardy Way"] = "R. Amazonas",
    
        ["Senora Way"] = "Rod. Transbasiliana",
    
        ["Glory Way"] = "R. Amparo",
        ["Bridge Street"] = "Av. Anhaia Mello",
        ["Tangerine Street"] = "R. Alcidez Munhoz",
        ["West Mirror Drive"] = "R. Francisco Polito",
        ["Nikola Avenue"] = "R. Américo Cioffi",
        ["Mirror Place"] = "R. Costa Barros",
        ["East Mirror Drive"] = "R. Olimpia",
        ["Utopia Gardens"] = "R. Campo Limpo",
        ["Nikola Place"] = "R. Lombroso",
        ["Capital Boulevard"] = "Av. Higienópolis",
        ["North Archer Avenue"] = "R. Frei Caneca",
        ["Spanish Avenue"] = "Alameda Tiête",
        ["Mad Wayne Thunder Drive"] = "Av. Europa",
        ["Picture Perfect Drive"] = "R. Francisco Ferrari",
        ["Sam Austin Drive"] = "R. Cel. Bonfim",
        ["Americano Way"] = "R. Cel. Soares",
        ["Richman Street"] = "R. do Matão",
        ["Ace Jones Drive"] = "Alameda Porto",
        ["Hangman Avenue"] = "R. Conde de Linhares",
        ["Hillcrest Ridge Access Road"] = "R. Portugal",
        ["Hillcrest Avenue"] = "R. Alemanha",
        ["Normandy Drive"] = "R. França",
        ["Kimble Hill Drive"] = "R. Argentina",
        ["Lake Vinewood Drive"] = "R. Estados Unidos / Represa",
        ["Lake Vinewood Estate"] = "R. Nino Crespi / Represa",
        ["Whispymound Drive"] = "R. Alasca",
        ["Wild Oats Drive"] = "R. Holanda",
        ["North Conker Avenue"] = "R. André Bonotti",
        ["Clinton Avenue"] = "R. Rosália Grisi Sandoval",
        ["Didion Drive"] = "R. Sueçia",
        ["Cox Way"] = "R. Suiça",
        ["South Mo Milton Drive"] = "R. Italia",
        ["Cockingend Drive"] = "R. México",
        ["Dunstable Drive"] = "R. Durval de Morais",
        ["Greenwich Way"] = "R. Itaim Bibi",
        ["Dunstable Lane"] = "R. Santos Doumont",
        ["Caesars Place"] = "R. Cubatão",
        ["Rockford Drive"] = "R. Colombia",
        ["Eastbourne Way"] = "R. Cuba",
        ["Cougar Avenue"] = "Travessa Doze",
        ["Bay City Incline"] = "Av. Jaguaré",
        ["Playa Vista"] = "R. Camargo",
        ["Decker Street"] = "R. Alvarenga",
        ["Ginger Street"] = "R. Vergueiro",
        ["Calais Avenue"] = "Av. Roberto Marinho",
        ["Shank Street"] = "Jardim Sao Bento / CAvPM",
        ["Tackle Street"] = "Marina Interlagos",
        ["Lindsay Circus"] = "R. Luiz schwelm",
        ["Equality Way"] = "R. Bartolomeu Zunega",
        ["Conquistador Street"] = "Travessa Alberto Campos",
        ["Magellan Avenue"] = "Av. do Emissário ",
        ["Cortes Street"] = "Travessa Domingos Assunção",
        ["Vitus Street"] = "R. Marcos Azevedo",
        ["Aguja Street"] = "R. Teodoro Sampaio",
        ["Goma Street"] = "R. William Navarro",
        ["Atlee Street"] = "R. Daniel Soares",
        ["Melanoma Street"] = "R. Bento Frias",
        ["Rub Street"] = "Marina Interlagos / Praia",
        ["Tug Street"] = "Marina Interlagos / Praia",
        ["Invention Court"] = "R. Pacatuba",
        ["Imagination Court"] = "R. Matias Gomes",
        ["South Arsenal Street"] = "R. João Schmidt",
        ["Mutiny Road"] = "R. Tapanan",
        ["Autopia Parkway"] = "R. Iguatinga",
        ["Exceptionalists Way"] = "R. Tamoios",
        ["Greenwich Parkway"] = "R. Toré",
        ["Grove Street"] = "R. da Paz",
        ["Crusade Road"] = "R. Joaquim Nabuca",
        ["Steele Way"] = "R. João Pimenta",
        ["Forum Drive"] = "R. Rodrigo Bonfim",
        ["Abattoir Avenue"] = "EcoPatio / Porto",
        ["Voodoo Place"] = "Libra Terminal",
        ["Kortz Drive"] = "Av. Adriano Bertozzi",
        ["Sandcastle Way"] = "Travesa Alberto Santos",
        ["Gentry Lane"] = "R. Russia",
        ["Swiss Street"] = "R. Paraguai",
        
        ["Sustancia Road"] = "Rod. Mario Covas",
        ["Amarillo Vista"] = "R. Botuporã",
        ["Labor Place"] = "R. Colombo",
        ["Amarillo Way"] = "R. Santa Cruz",
        ["Tower Way"] = "R. Laudelino Freire",
        ["Fudge Lane"] = "R. Silvio Romero",
    
        ["South Shambles Street"] = "R. Parapuã",
        ["Hanger Way"] = "R. Panambí",
        ["Orchardville Avenue"] = "R. São Luis",
        ["Dry Dock Street"] = "R. da Sorte",
        ["El Burro Boulevard"] = "Alameda Barros",
        ["Supply Street"] = "Av. Carlos Hank",
    
        ["Signal Street"] = "R. Paschoal Leonardi",
        ["Chum Street"] = "Av. José Carlos Pace",
        ["Plaice Place"] = "R. Celso Lara Barberis",
        ["Mount Hann Drive"] = "Av. Cel. Alan Henrique",
        ["Chupacabra Street"] = "Marimex / Docas",
        ["Pista de pouso1"] = "Aeroporto de Congonhas - CGH",
    },
    ["Weapon"] = {
        [`WEAPON_PISTOL`] = { name = "PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172254537386557500/Pistol-icon.png" },
        [`WEAPON_PISTOL_MK2`] = { name = "PISTOL MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172254349989257236/Pistol-mk2-icon.png" },
        [`WEAPON_PISTOL50`] = { name = "PISTOL 50", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172254712649764966/Pistol.png" },
        [`WEAPON_REVOLVER`] = { name = "REVOLVER", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172254836486590474/164px-Heavy-revolver-icon.png" },
        [`WEAPON_COMBATPISTOL`] = { name = "COMBAT PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172254949963468931/Combat-pistol-icon.png" },
        [`WEAPON_APPISTOL`] = { name = "AP PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255130008158268/Appistol-icon.png" },
        [`WEAPON_HEAVYPISTOL`] = { name = "HEAVY PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255241211756634/Heavy-pistol-icon.png" },
        [`WEAPON_SNSPISTOL`] = { name = "SNS PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255376939434014/Sns-pistol-icon.png" },
        [`WEAPON_SNSPISTOL_MK2`] = { name = "SNS PISTOL MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255477896319057/Sns-pistol-mk2-icon.png" },
        [`WEAPON_VINTAGEPISTOL`] = { name = "VINTAGE PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255595756265522/Vintage-pistol-icon.png" },
        [`WEAPON_MICROSMG`] = { name = "MICRO SMG", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255707064700928/164px-Micro-smg-icon.png" },
        [`WEAPON_MINISMG`] = { name = "MINI SMG", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255806704586832/164px-Mini-smg-icon.png" },
        [`WEAPON_SMG`] = { name = "SMG", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255892666851468/164px-Smg-icon.png" },
        [`WEAPON_SMG_MK2`] = { name = "SMG MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172255934307901561/164px-Smg-mk2-icon.png" },
        [`WEAPON_ASSAULTSMG`] = { name = "ASSAULT SMG", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256073705586761/164px-Assault-smg-icon.png" },
        [`WEAPON_GUSENBERG`] = { name = "GUSENBERG", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256371509571626/164px-Gusenberg-sweeper-icon.png" },
        [`WEAPON_MACHINEPISTOL`] = { name = "MACHINE PISTOL", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256467856916490/164px-Machine-pistol-icon.png" },
        [`WEAPON_COMPACTRIFLE`] = { name = "COMPACT RIFLE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256566548910190/164px-Compact-rifle-icon.png" },
        [`WEAPON_CARBINERIFLE`] = { name = "CARABINE RIFLE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256618684096512/164px-Carbine-rifle-icon.png" },
        [`WEAPON_CARBINERIFLE_MK2`] = { name = "CARABINE RIFLE MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256787563548712/164px-Carbine-rifle-mk2-icon.png" },
        [`WEAPON_BULLPUPRIFLE`] = { name = "BULLPUP RIFLE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256870019366952/164px-Bullpup-rifle-icon.png" },
        [`WEAPON_BULLPUPRIFLE_MK2`] = { name = "BULLPUP RIFLE MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172256890860883968/164px-Bullpup-rifle-mk2-icon.png" },
        [`WEAPON_ADVANCEDRIFLE`] = { name = "ADVANCED RIFLE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257006980169808/164px-Advanced-rifle-icon.png" },
        [`WEAPON_ASSAULTRIFLE`] = { name = "ASSAULT RIFLE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257086114111499/164px-Assault-rifle-icon.png" },
        [`WEAPON_ASSAULTRIFLE_MK2`] = { name = "ASSAULT RIFLE MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257110160064522/164px-Assault-rifle-mk2-icon.png" },
        [`WEAPON_SPECIALCARBINE`] = { name = "SPECIAL CARABINE", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257266888622150/164px-Special-carbine-icon.png" },
        [`WEAPON_SPECIALCARBINE_MK2`] = { name = "SPECIAL CARABINE MK2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257291756650546/164px-Special-carbine-mk2-icon.png" },
        [`WEAPON_PUMPSHOTGUN`] = { name = "PUMP SHOTGUN", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257346064502885/164px-Pump-shotgun-icon.png" },
        [`WEAPON_PUMPSHOTGUN_MK2`] = { name = "PUMP SHOTGUN 2", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257370055921764/164px-Pump-shotgun-mk2-icon.png" },
        [`WEAPON_SAWNOFFSHOTGUN`] = { name = "SAW OFF SHOTGUN", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257618560045168/164px-Sawed-off-shotgun-icon.png" },
        [`WEAPON_SNIPERRIFLE`] = { name = "FN FIVE SEVEN", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257657843888208/164px-Sniper-rifle-icon.png" },
        [`WEAPON_MUSKET`] = { name = "MUSKET", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257868037238866/164px-Musket-icon.png" },
        [`WEAPON_PETROLCAN`] = { name = "PETROL CAN", image = "https://cdn.discordapp.com/attachments/1022113603677065297/1172257910148042794/94px-Petrolcan-icon.png" },
    },
}
